### ISSUE TITLE
Get list of what's been polyfilled

### ISSUE THREAD

**Issue by siassaj** [polyfillpolyfill/polyfill-service#1074]
Hi all, firstly thank you for this useful service.

We recently came across a string of exceptions on our tracker to do with Symbol.iterator, Long story short, it's highly likely the UA was being spoofed causing it to overrided Symbol.iterator (among other things), breaking everything. I verified this effect on my local.

We also regularly get exceptions like 'Promise is not defined' despite requesting es6 features.
So it was suggested that we add more context to our exception tracker, so that it knows if polyfill.io was even loaded and if so what polyfills were requested and then actually applied.

Upon examining polyfill.js it's evident that the information is sent through only as comments, so it's already available data, just not put into memory anywhere.

So the question now is, is this something that the team would be interested in having? If so I can take a look to making a fork,

**Comment by triblondon** [comment]
Hi @siassaj,

I think this is an interesting idea, and we're not opposed to having it.  [This is the part](https://github.com/Financial-Times/polyfill-service/blob/master/lib/index.js#L175-L178) of the code that builds the list of features that are included in the bundle, so you could add an alternative mode here to output that data in a machine readable form.  I'd consider activating this based on the presence of the RUM opt-in, `rum=1` on the query string, since that mode is for instrumenting the operation of the service.  Alternatively, maybe we could have a new param, `debug=1` which would export debug data onto a `Polyfill_IO` global object.

**Comment by triblondon** [comment]
I'm going to close this as we don't like to leave feature request issues open if no-one is working on them. If you want to make a PR for this though we'd be delighted to see it.
