### ISSUE TITLE
Including the Intl polyfill

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#108]
Hi,

I'd love to help get the [Internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) polyfill in this service. It's complicated because it includes a lot of extra files besides the main polyfill. See https://github.com/andyearnshaw/Intl.js/tree/master/locale-data/jsonp.

If we can agree on a way to include it, I'll be happy to send a pull request.

**Comment by triblondon** [comment]
@juandopazo where do you feel like we should take this one?

**Comment by caridy** [comment]
More and more people asking us how to load the Intl polyfill, let's make this happen.

**Comment by slorber** [comment]
+1 and it would be nice to be able to specify by query string the languages we want to load data for

**Comment by johanneslumpe** [comment]
Just as @slorber said, being able to only load the locales we want would be a huge plus here. Instead of having to push down all the available locales out there.

But in general: really looking forward of having this available.

**Comment by sebastienbarre** [comment]
@johanneslumpe This doesn't do the trick for you?

```
  require('intl/Intl');
  require('intl/locale-data/jsonp/en.js');
  require('intl/locale-data/jsonp/fr.js');
```

to load en/fr, as opposed to:

```
require('intl'); 
```

Which brings everything.

**Comment by johanneslumpe** [comment]
@sebastienbarre No that actually works :) And I'll stick with that for now. But it might be nice to now having to bundle this for browsers which already support `Intl`

**Comment by juandopazo** [comment]
@triblondon we need to answer two questions:
1. Do we want the Intl source code in this package or to just reuse it from the npm package?
2. Do we treat locales as polyfills or as a special case like `features=Intl&locales=en-US,fr-FR`?

**Comment by triblondon** [comment]
The easiest answer here that requires no changes to the service is:
- Add `Intl` as a polyfill with the core lib, copied from its source repo, but with repo URL listed in config to allow it to be updated easily
- Add additional separate polyfills for each locale under a sensible naming scheme.  I'm not sure whether there's a property available in `Intl` that represents a locale - if there is, then it can be named for that, eg `Intl.localesAvailable.en-US`.  However I suspect this doesn't exist, in which case strictly speaking the locale polyfills should have a `~` prefix, like HTML5shiv does, and perhaps we'd call them eg. `~IntlLocale.en-US`.  This prefix indicates that the name of the polyfill is not a JavaScript global.

Sure, we could add an npm dependency on the source repo, and we could add some special casing to the service to support a locale list, but those both make the service more inconsistent or more complicated, so I'd favour using the mechanism we already have.  Using the above method, you would then get Intl with en-us and fr-fr using:

`polyfill.min.js?features=Intl&~IntlLocale.en-US&~IntlLocale.fr-FR`

**Comment by juandopazo** [comment]
The problem is that there are _a lot_ of locale files. See https://github.com/andyearnshaw/Intl.js/tree/master/locale-data/jsonp. We can't just create a folder under `polyfills/` for each one.

**Comment by triblondon** [comment]
How about we reorganise the polyfills dir so that rather than having dot delimiters in object names, we descend into sub folders? Eg.

```
Array.prototype.forEach => Array/prototype/forEach
```

And intl locales could be under `Intl/~locales/` eg. `Intl/~locales/en-GB`. The ~ here indicating a name that is not a JS property. Would that work?

**Comment by triblondon** [comment]
If you were keen on syntactic sugar you could add capability to the service to expand shortcuts like

`features=Intl.~locales.[en-US,en-GB]`

But that doesn't seem necessary for an initial implementation.

**Comment by caridy** [comment]
I like `Intl/~locales/en-GB`. I don't think we need to provide sugar to load multiple locales at once, because that's not very common, you normally load one, and `en` is built-in in the library. If they can do: `featues=Intl&Intl/~locales/en-GB&Intl/~locales/fr-FR` it will be enough in case they really want to do such thing.

**Comment by juandopazo** [comment]
Sounds good!

**Comment by triblondon** [comment]
If I make the changes to the service, can you guys do the polyfill data?

**Comment by juandopazo** [comment]
Yup!

**Comment by triblondon** [comment]
Just figuring out how to do this.  Would you guys object to keeping the existing syntax for the query string, so the example we were talking about earlier would be `featues=Intl&Intl.~locales.en-GB&Intl.~locales.fr-FR`?  There are two advantages to this:
- It makes more sense for most of our polyfills where we're polyfilling a web API that actually does have that object name, like `Array.prototype.forEach`.  It would be less useful to have to refer to that as `Array/prototype/forEach`.
- It's backwards compatible

If this is OK, then the change is really simple, and only affects the way we run the build step to generate the sources.json file, rather than requiring any changes to the service itself.

**Comment by triblondon** [comment]
OK, see https://github.com/Financial-Times/polyfill-service/pull/377

**Comment by ericf** [comment]
Cool, so looks like #377 should work. Thanks for making the change!

**Comment by caridy** [comment]
agree, #377 looks good, and it looks far more flexible than what we have internally.

**Comment by triblondon** [comment]
Good news, thanks for the feedback.  I suggest you guys add Intl to the `subfolder-structure` branch, so we can make sure this new approach will work with how we're proposing to treat Intl, and also because there isn't really a compelling use case for the subfolder structure until we have Intl as part of the library.

**Comment by triblondon** [comment]
@juandopazo @caridy do you have an idea of when you might be doing this?

**Comment by kellylawson** [comment]
I've been trying to find a decent solution to this problem all day and just stumbled across this issue.  The solution looks perfect - when will it be available?

**Comment by triblondon** [comment]
As soon as someone implements it :-)

**Comment by caridy** [comment]
@triblondon I'm back from sabbatical, I will give it a try in the next few days.

**Comment by triblondon** [comment]
See #419
