### ISSUE TITLE
IntersectionObserver is not defined

### ISSUE THREAD

**Issue by shtse8** [polyfillpolyfill/polyfill-service#1138]
I have got some error reports with the following message:
```
IntersectionObserver is not defined
```

Reports received from user-agent:
```
Facebook 115.0.0
Facebook 109.0.0
Facebook 114.0.0
Facebook 113.0.0
```

I think that polyfill.io cannot identify Facebook webview user-agent and cannot provide the correct polyfill.

So I have tried to add `unknown=polyfill`, but with no luck.
An error was caught:
```
Script error.
```

**Comment by shtse8** [comment]
Also, setting `unknown=polyfill` will cause many errors with our scripts.
for example: `getComputedStyle` returns `undefined` in modern browser. 
I have tried android webview and the browser has implemented `getComputedStyle` but due to the unknown user agent, polyfill.io will respond all polyfills.
therefore, `unknown=polyfill` cannot use at any time. I would like to suggest `Polyfill.io` not to polyfill if the function exists.

**Comment by shtse8** [comment]
```
https://cdn.polyfill.io/v2/polyfill.min.js?features=IntersectionObserver,requestAnimationFrame&excludes=Element,getComputedStyle&unknown=polyfill
```

this request works fine now. But I don't know how about if browsers don't have `Element` and `getComputedStyle`. I think `Element`, `getComputedStyle` are not working properly.

**Comment by triblondon** [comment]
Hi @shtse8.  To help us debug this, could you give us some more information:

1. The full `User-Agent` header of the browser in which you observed the problem
2. A reduced test case using a tool like jsbin.com that loads only polyfill.io and as much inline script as is needed to trigger the issue

Without this, I can make an educated guess that Facebook browser is being treated as an unknown UA, and that's why you need `unknown=polyfill` to make it work.  However, `unknown=polyfill` gives you *all* polyfills, which may include those that don't work in that browser.  Results may be unpredictable.  I would suggest adding `flags=gated` when using this mode.

We are already tracking an issue with identifying Facebook browser as #990, so if that's your issue you can follow it there, otherwise feel free to reopen with the info above.

**Comment by shtse8** [comment]
Yes, I think it is the same issue. But I would not expect giving all polyfills will cause errors, once it is, it is very dangerous for those unknown user agent. why don't checking the existance of the methods instead of just overriding all?

**Comment by gheoan** [comment]
@shtse8 `flags=gated` does exactly that. See https://polyfill.io/v2/docs/api.

**Comment by shtse8** [comment]
@Gheoan Thanks. I miss this flag. how about the `always` flag? i can't understand the description.
