### ISSUE TITLE
fetch not served to Chrome 38

### ISSUE THREAD

**Issue by jonashaag** [polyfillpolyfill/polyfill-service#1212]
https://cdn.polyfill.io/v2/polyfill.js?features=fetch&ua=Mozilla/5.0%20(Linux;%20Android%205.0.2;%20SAMSUNG%20SM-T555%20Build/LRX22G)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20SamsungBrowser/3.3%20Chrome/38.0.2125.102%20Safari/537.36

This is Chrome 38, but fetch API is only supported in Chrome 42+

**Comment by ruiaraujo** [comment]
You need to use unknown=polyfill as an option since that is Samsung Browser 3.3 which is not supported.

**Comment by JakeChampion** [comment]
Samsung Internet versions less than 4 are difficult for us to support because we don't have devices with that browser available to test on. We can't do a direct mapping to Chrome versions as Samsung Internet adds and removes feature from the Chrome version it is based upon.

We chose to only support Samsung Internet version 4 and above.

@ruiaraujo's advice to include `unknown=polyfill` in your polyfill.io request should solve your issue.
