### ISSUE TITLE
"TypeError: Cannot convert a Symbol value to a string" Happening on Samsung Browser

### ISSUE THREAD

**Issue by rubencodes** [polyfillpolyfill/polyfill-service#1213]
Some of my users on Android 5.x Samsung Browser are experiencing this error caused by the Polyfill.io service when I load polyfills such as `Array.prototype.find` and have the `unknown=polyfill` flag set. I was able to trace the error back to this line:

<img width="1186" alt="screen shot 2017-05-30 at 4 33 16 pm" src="https://cloud.githubusercontent.com/assets/1036549/26609780/069bf744-4558-11e7-82b1-f120f2e59a7a.png">

From the `Object.defineProperty` polyfill that is loaded in as a dependency. I looked through the `Array.prototype.find` code myself and see no reason this should be happening, as it should receive a simple string in the property parameter...

The user agents I've seen affected are:
`Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG-SM-G530AZ Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36`
`Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J320P Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Mobile Safari/537.36`
`Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G530P Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36`
`Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G530T Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36`

I'm pretty sure this error would be avoided if the SamsungBrowser/3.x were just treated like  Chrome/38.x, as that wouldn't require an Object.define polyfill. Is there any way to do this?

**Comment by ruiaraujo** [comment]
You can use the exclude option for Object.defineProperty.

Even IE8 supports it.

**Comment by JakeChampion** [comment]
@rubencodes Samsung Internet versions less than 4 are difficult for us to support because we don't have devices with that browser available to test on. We can't do a direct mapping to Chrome versions as Samsung Internet adds and removes feature from the Chrome version it is based upon. 

We chose to only support Samsung Internet version 4 and above.

If you do not support the below browsers then you can exclude `Object.defineProperty` as @ruiaraujo has mentioned --
```
"firefox": "3.6",
"safari": "4 - 4.1",
"ios_saf": "4.3",
"firefox_mob": "3.6",
"ie": "6 - 8"
```

If this answers your question, feel free to close the issue :-)

**Comment by rubencodes** [comment]
Thank you! That helps :)
