### ISSUE TITLE
Wrong Safari Feature detection

### ISSUE THREAD

**Issue by caub** [polyfillpolyfill/polyfill-service#1231]
Safari Version 10.0.1 (12602.2.14.0.7) with userAgent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14` does not have fetch available in window, but the polyfill for it https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_12_1)%20AppleWebKit/602.2.14%20(KHTML,%20like%20Gecko)%20Version/10.0.1%20Safari/602.2.14 doesn't provide fetch

related #1216

**Comment by JakeChampion** [comment]
That is because `fetch` is not in the default set of polyfills which is what you are requesting. If you want `fetch` alongside the default set you can make a request like this https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch

Here it is using the UA you provided, you can see that it supplies fetch polyfill -- https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch&ua=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_12_1)%20AppleWebKit/602.2.14%20(KHTML,%20like%20Gecko)%20Version/10.0.1%20Safari/602.2.14

**Comment by caub** [comment]
thanks, ok, will read the docs better
