### ISSUE TITLE
Splitting this project into two: the server and the polyfill collection

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#125]
Hi!

What do you think about splitting this project into two? Basically there's the service itself, which optiimizes the serving of polyfills, and there's the polyfill collection that @jonathantneal started and is dear to his heart. Do you think it'd make sense to split it into two? It would at least allow for us to use the collection while we try a different approach on the serving side.

**Comment by triblondon** [comment]
@juandopazo this is also being requested by teams at FT, at least they want to be able to guarnatee that polyfills will not change without their knowledge.  Since we have the problem of the service being an integral part of the testing of the polyfills, I suggest the following:
1. Add a grunt task to clone older versions of the polyfill library into the file tree.  Propose `/polyfills/_versions/{version}/`.  Run this as part of pre-deploy build.
2. Load sources from all versions, with the ones in the root of `/polyfills` being considered 'latest'
3. Add support for a querystring argument `libraryVersion` on the service, which will pass through to the library
4. Support an option `libraryVersion` on the `getPolyfillString` API method, which switches to the appropriate library version (or uses latest if unable to find one
5. Report which version of the libary is being used in the bundle header comment.

What do you think?  Would you prefer to detach the service completely from the library to suit your needs better?  If so how would you do the testing?

**Comment by juandopazo** [comment]
I've been wondering about the testing part. The current test suite tests both the behavior of the polyfill and the behavior of the service (it's not using the `always` flag). I'm guessing it shouldn't be very hard to test the polyfills without the optimization based on the browser.

But so far the only reason why separating them would be desirable would be to avoid installing the dependencies which makes build tasks slower. And that can be worked around. So for now using the service as it is seems to be working.

Also, if you start supporting versions we might just switch to using your service as a plain old npm dependency :smile:

**Comment by triblondon** [comment]
OK, in that case I propose closing this issue in favour of https://github.com/Financial-Times/polyfill-service/issues/242 (Allow version-locking / shrinkwrapping of polyfill library version in request)

**Comment by triblondon** [comment]
Let's assume yes :-)
