### ISSUE TITLE
Consider removing warning for "all" and documenting the feature group

### ISSUE THREAD

**Issue by tracker1** [polyfillpolyfill/polyfill-service#1256]
When you use `?feature=all` you get the following warning.

> Using the `all` alias with polyfill.io is a very bad idea. In a future version of the service, `all` will deliver the same behaviour as `default`, so we recommend using `default` instead.

I suggest removing this, and documenting the feature, for the following reasons.

* it allows the same url to be used/cached by multiple sites
* most options are already in most green browsers, mitigating the size/impact of the download

This allows a given website to simply reference the "same" option as everyone else.  Which means it's more likely for a browser to have an existing reference to the script.  Beyond this, it allows, with proper cache headers `Vary: User-Agent`, it is very cacheable, with even a 2-week timeout, that would allow for caching to be very effective.  With multiple supported websites targeting the same base url, it becomes more likely to be cached all the same.

Also, for a current chrome release, there's only a handful of polyfills, similar for other current browsers.  Meaning that the warning is less meaningful, as the number of unsupported features grows smaller, not bigger over time.  Better documentation on grouping may be another option as well.  Even the largest polyfill, `fetch`, is only needed on IE, and older browsers.

**Comment by triblondon** [comment]
No, we will definitely not be resuming support for `all`.  Notably this is because using `all` in a browser that does not support `Intl` results in a 25MB polyfill bundle with every single locale dataset included.  It is also problematic if we consider adding more such enormous polyfills in the future (which would then automatically roll out to anyone that had unwisely opted for `all`.
