### ISSUE TITLE
Improve output, adjust vary header

### ISSUE THREAD

**Issue by tracker1** [polyfillpolyfill/polyfill-service#1257]
Change the vary header 

From: `vary: Accept-Encoding`
To: `vary: Accept-Encoding,User-Agent`

**Comment by triblondon** [comment]
We already include `Vary: User-Agent` in the HTTP response, but it looks as though this is now split across multiple headers:

![image](https://user-images.githubusercontent.com/1735391/29198985-14bbf4f6-7e8c-11e7-88a1-33e65d63acc4.png)

@JakeChampion Is that intentional?  I am not sure whether user agents will honour multiple vary headers (I should test this!)

**Comment by JakeChampion** [comment]
The logic around the Vary header hasn't changed for a very long time, I assume user agents support it as we have not had any issues raised around this before.

**Comment by tracker1** [comment]
Sorry, I hadn't noticed the second header when looking at the response from the public server, only the Accept-Encoding.

@triblondon agents will respect both when on the same header, or separate header lines in the same response.
