### ISSUE TITLE
Down? 404 errors

### ISSUE THREAD

**Issue by christopherdarling** [polyfillpolyfill/polyfill-service#1327]
Loading https://cdn.polyfill.io/v2/polyfill.min.js?features=default in Chrome and Edge (with a cleared cache) all return the Heroku "There's nothing here" blue page. 

The examples page all but the 'Basic Case' fail to load (agian, Chrome and Edge)

![image](https://user-images.githubusercontent.com/178039/30424458-f34641c4-993d-11e7-81b8-49c5732175a3.png)

Using qa.polyfill.io there seems to be no problem

**Comment by jar-miracle** [comment]
It responds again now.

**Comment by triblondon** [comment]
@christopherdarling we had an issue with a deploy just now.  We rolled it back, and are now back up.  We're doing a fuller analysis and will post more details here.

**Comment by wheresrhys** [comment]
Does polyfill.io have smoke tests built into its CI pipeline (we have code in ft.com you could canibalise). 

Also, maybe canary releases should be a consideration given polyfill.io's web-breaking potential these days?

**Comment by triblondon** [comment]
This would have been an isolated issue because it only affected origin fetches during a 10 minute period, and bundles are cached for a week. The biggest impact would have been as a result of stale-while-revalidate requests that pulled the 404 response from heroku and considered it a valid replacement for the stale object in cache. Jake and I are working on a PR to resolve that.

Canary VCL would introduced more forked paths through the code based on environment, which is rarely a good thing, so I'd prefer to make the QA VCL a better test of what will happen in prod.

**Comment by JakeChampion** [comment]
This issue was to do with a deployment of our vcl which contained a bug where the wrong Host header was being sent to Heroku. This meant that Heroku was routing the request to a non-existent application.

Since this bug was introduced we have updated the VCL in order to allow us to test the VCL with the production backends prior to deploying the VCL to our production Fastly service.
