### ISSUE TITLE
Object.getOwnPropertyDescriptor(Set.prototype, 'size') returns undefined in IE11

### ISSUE THREAD

**Issue by JamesSingleton** [polyfillpolyfill/polyfill-service#1359]
Browser: IE11 version 11.0.9600.18762

Polyfill URL: https://cdn.polyfill.io/v2/polyfill.min.js

Error: Unable to get property 'get' of undefined or null reference

When running the non-minified version, my console points to the following code:
```
var isSet;
    if (hasSet) {
        var setSize = Object.getOwnPropertyDescriptor(Set.prototype, 'size').get;
        isSet = function (set) {
            try {
                setSize.call(set);
                return true;
            } catch (e) {
                return false;
            }
        };
    }
```

The line in particular is `var setSize = Object.getOwnPropertyDescriptor(Set.prototype, 'size').get;` If I run Object.getOwnPropertyDescriptor(Set.prototype, 'size') it returns undefined.

**Comment by kdzwinel** [comment]
We are seeing the same error in:
- various versions of Opera Mini
- Chrome Mobile 30.0.0
- Android 4.4.2
- Safari 7.x

Depending on browser we get:
- > Cannot read property 'get' of undefined
- > Uncaught exception: TypeError: Cannot convert 'Object.getOwnPropertyDescriptor(Set.prototype,"size")' to object
- > TypeError: 'undefined' is not an object (evaluating 'Object.getOwnPropertyDescriptor(Set.prototype,"size").get')

It looks like issues started on October 13th.

**Comment by JamesSingleton** [comment]
Hi @kdzwinel, any idea on what is causing this? The issue is not present in Edge, Chrome or FireFox. For the time being, we have found a work around by using https://cdn.polyfill.io/v2/polyfill.js?excludes=Array.from. By no means is this an absolute fix, and if you need Array.from, use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by JakeChampion** [comment]
Hi, I tried to replicate the issue but I see it working correctly in IE11 on Browserstack.
![Screenshot of IE11 on BrowserStack showing the code not causing an error](https://user-images.githubusercontent.com/1569131/31633187-8163d272-b2b7-11e7-9204-ea573ec3e2f8.jpg)


You've got an error in your website that you've tracked down to the code you're loading from the polyfill service.

Could you create a test case using an online tool like JSBin, which loads only the polyfill service script, and then includes inline any code required to trigger the problem (which should be no more than a few lines).

After you have made the test case, can you comment on this issue, and include:
- A description of the problem (what you expected, what actually happened)
- A link to your test case on JSBin (or jsfiddle/codepen/whatever)
- The exact name and version number of the browser you're testing in
- If relevant, the console output or a screenshot of the problem

We ask for a JSBin demo because often these kinds of errors are actually errors in the host website's code, and even if they are a problem in the polyfill, we don't have the resources to debug your application. Please also make sure you disable any browser plugins when you are testing in JSBin, so you are certain that you are only running the test code.

**Comment by JamesSingleton** [comment]
@JakeChampion interesting that JSBin shows no error, but when running it on our site it shows an issue. Furthermore, it is interesting that @kdzwinel is seeing the same error I described in other OS/browsers as well, so I am not entirely sure what is going on.

**Comment by kdzwinel** [comment]
It took me good half of the day but here we go: http://output.jsbin.com/cufutay (can be reproduced e.g. on IE10). Google ads script is causing the issue.  If you change the order and load polyfillio before google ads, everything will work fine.

@JakeChampion - was a new version of polyfillio deployed around 13th? If not, that would mean that Google updated their script causing the issue. I can try reaching out to them.

**Comment by JakeChampion** [comment]
@kdzwinel Thanks for that jsbin! The last release was 14 days ago on October 3rd. I would think this is a Google Ads script issue.

**Comment by JamesSingleton** [comment]
Awesome @kdzwinel! I will take a look at it today and let you know! Thank you!

**Comment by JamesSingleton** [comment]
@kdzwinel and @JakeChampion,

I no longer get the error on that JSBin you provided, not sure if you guys fixed something or Google Ads fixed something.

**Comment by kdzwinel** [comment]
Yep, I can see that they changed the script since yesterday (removed Map and WeakMap polyfills of their own), and error is no longer thrown. I like to think it's thanks to my bug report: https://twitter.com/kdzwinel/status/920290340573208576 😉 Issue can be closed 🎉

**Comment by JakeChampion** [comment]
Thanks for the bug report and everything @JamesSingleton  and @kdzwinel 👍

**Comment by JamesSingleton** [comment]
@JakeChampion and @kdzwinel, no problem and thank you for looking into this!
