### ISSUE TITLE
HTMLCanvasElement.prototype.toBlob is not served to IE 11

### ISSUE THREAD

**Issue by philipstanislaus** [polyfillpolyfill/polyfill-service#1364]
Request:

https://cdn.polyfill.io/v2/polyfill.js?features=HTMLCanvasElement.prototype.toBlob 

Here is the response from the polyfill service:

```js
/* Polyfill service v3.22.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: ie/11.0.0
 * Features requested: HTMLCanvasElement.prototype.toBlob
 *  */

/* No polyfills found for current settings */

```

Browser UA string is correctly recognized as IE 11, other polyfills such as https://cdn.polyfill.io/v2/polyfill.js?features=String.prototype.includes work as expected.

Tested in Google Chrome with UA spoofing and in a Windows 7/IE 11 virtual machine from https://developer.microsoft.com/en-us/microsoft-edge/, both fail.

Any ideas how to solve this issue?

**Comment by JakeChampion** [comment]
Thanks for the bug report, the issue is the semver range was invalid, if no spaces are around the dash character, the semver module interprets it as specifically version `10-11` and not as versions `10.*.*` to version `11.*.*`. PR to fix this -- https://github.com/Financial-Times/polyfill-service/pull/1365

**Comment by philipstanislaus** [comment]
Thanks for your very fast response and fix! 🎉
