### ISSUE TITLE
IE11 HierarchyRequestError

### ISSUE THREAD

**Issue by wbusby88** [polyfillpolyfill/polyfill-service#1428]
Hi,

We received an issue from a client using an older version of IE11 - version 11.0.9600.18837. It works in the version we have on our machines, which is 11.608.15063.0. Here are screenshots from their machine:

![image](https://user-images.githubusercontent.com/9214254/34101890-29336442-e3df-11e7-9fbf-957c1fe8874e.png)
![image](https://user-images.githubusercontent.com/9214254/34101995-6ee82ef0-e3df-11e7-85f7-f6d1acc637ea.png)

This is the script src of polyfill.io we're using:

https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes,Array.prototype.find,Element.prototype.remove

Any help on this would be appreciated.

Thanks.

**Comment by njbotkin** [comment]
I think this is another instance of #875.  I ran into this on Android 4.4.3 webview.  I added the `gated` flag, which kept the unnecessary Element polyfill from executing.  Try

http://cdn.polyfill.io/v2/polyfill.min.js?features=default|gated,Array.prototype.includes,Array.prototype.find,Element.prototype.remove

or

http://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes,Array.prototype.find,Element.prototype.remove&flags=gated

**Comment by wbusby88** [comment]
Thanks, I'll try it out. We're not going to deploy until after the new year. I will comment back if this fix solves the issue.

**Comment by marc-bouvier** [comment]
I can reproduce this issue. Instructions can be found here : https://marc-bouvier.github.io/test-polyfill-io/index.html I rewrote them in the following text.

**Problem**
In Internet Explorer 11, When a site is in "Local intranet" security zone, and using cdn.polyfill.io, **ie/7.0.0 is detected instead of ie/11.0.0**

**Reproduce**

1. On Windows 7, Internet Explorer 11 (you can find virtual images from microsoft here : https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
2. Open this page on Internet Explorer 11 : https://marc-bouvier.github.io/test-polyfill-io/index.html
3. Then, open internet explorer "internet options"

![](https://marc-bouvier.github.io/test-polyfill-io/01_internet_options.JPG)

4. Add the domain "https://marc-bouvier.github.io" to "Local intranet" sites.

![](https://marc-bouvier.github.io/test-polyfill-io/02_Advanced.JPG)
![](https://marc-bouvier.github.io/test-polyfill-io/03_add.JPG)
![](https://marc-bouvier.github.io/test-polyfill-io/04_added.JPG)

5. Open page inspection (F12) and reload the page
On the javascript console you will have the error : HierarchyRequestError

![](https://marc-bouvier.github.io/test-polyfill-io/05_javascript_console_error.JPG)

6. Open Debugger tab and look at the comment section of "polyfill.js" file
ie/7.0.0 is detected instead of ie/11.0.0

![](https://marc-bouvier.github.io/test-polyfill-io/06_polyfill-detects-wrong-IE-_version.JPG)

**Comment by justin-nodeboy** [comment]
+1, I get this error as well.

**Comment by JakeChampion** [comment]
@marc-bouvier Thank you for the detailed bug report! I think I know how to solve the issue because of your excellent reproduction steps :-)

**Comment by DonGissel** [comment]
So... any news on this? We are seeing this problem in production on certain machines now, too.

**Comment by azenkovets** [comment]
+1 Any new on this?

**Comment by waghcwb** [comment]
I can confirm this error too on Windows 10 and IE11
![image](https://user-images.githubusercontent.com/6169950/50770798-a88d1980-126f-11e9-8cb4-34f662b1160a.png)

**Comment by JakeChampion** [comment]
Hi all, I believe this is fixed in https://polyfill.io/v3/polyfill.js. I will be closing the issue as I can no longer reproduce the bug.

If you can still reproduce the bug using version 3 of the service, please comment on the issue and I will reopen it.

**Comment by ricardograca** [comment]
This is still an issue when using the `flags=always` option. This html file will trigger the error on IE11:

```html
<html>
<head>
  <script src="https://polyfill.io/v3/polyfill.js?flags=always"></script>
</head>
</html>
```

**Comment by JakeChampion** [comment]
It is recommended to not use `always` on all polyfills without  also including `gated` on all polyfills for this very reason.

What is your use-case for `https://polyfill.io/v3/polyfill.js?flags=always`? Perhaps we can solve your issue without having to resort to always including the polyfills even when a browser does not require them.

**Comment by ricardograca** [comment]
What does `gated,always` even mean? I would expect this to be to a `OR` type of situation.

The issue that I'm having is that the `fetch` polyfill (and maybe the others as well) is not being loaded in IE11 and some versions of the Facebook browser. The strange thing is that it's loaded correctly in the VM I have with IE11 and on crossbrowsertesting.com, so I was trying to get the polyfills to always load.
