### ISSUE TITLE
Array.from tests fails where natively implemented in FF 32

### ISSUE THREAD

**Issue by samgiles** [polyfillpolyfill/polyfill-service#146]
See: https://github.com/mathiasbynens/Array.from/issues/13

**Comment by triblondon** [comment]
I'm pretty strongly anti detect variants, too much complexity, and also we're supposed to be detecting a thing that is consistent across browsers - varying the detect for that is probably not a good road to start down. 

So to recap, currently we show FF32 as not polyfillable on our compat table, but we still target it, so we'll correct their implementation provided that you serve the polyfill without feature detects.  If you gate it with a feature detect, it will detect the wobbly native implementation and not replace it.  This is a bit annoying but not exactly a big problem, especially since the actual impact of the specific failure is pretty minor.

I guess we keep this open but I don't think it's something we should consider a bug in the polyfill.

**Comment by triblondon** [comment]
We're not going to take any action here.
