### ISSUE TITLE
Object.entries not served with ios_saf/10.0.0

### ISSUE THREAD

**Issue by vgavro** [polyfillpolyfill/polyfill-service#1599]
Object.entries not served with ios_saf/10.0.0 (iPhone 6 Safari)
```
Polyfill service v3.25.1
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: ios_saf/10.0.0
 * Features requested: default-3.4,es6,es7,fetch
 * 
 * - fetch, License: MIT
 * - URL, License: CC0 (required by "default-3.4")
 * - Math.clz32, License: CC0 (required by "es6")
 * - Math.sign, License: CC0 (required by "es6")
 * - Object.is, License: CC0 (required by "es6")
 * - String.prototype.repeat, License: CC0 (required by "es6") */
```

**Comment by SpadeAceman** [comment]
I ran into this same issue - turns out you actually need to add `es2017` to your list of requested features to get `Object.entries` (and `Object.values`).

http://2ality.com/2016/02/ecmascript-2017.html

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/entries/config.json

**Comment by JakeChampion** [comment]
@SpadeAceman That's correct, you can explicitly request `Object.entries` or use the alias `es2017`.
