### ISSUE TITLE
Website: 404 on all polyfill sources

### ISSUE THREAD

**Issue by JonGarbayo** [polyfillpolyfill/polyfill-service#1715]
Hi!

On https://polyfill.io/v2/docs/features/, all links to polyfill sources in hamburger menus lead to a GitHub 404 page.

It seems the repo paths have been changed, but the website didn't receive the appropriate update :bug:

Have a good day!

**Comment by benjclark** [comment]
Yep, still an issue

**Comment by lewisje** [comment]
As an example, on [this page](https://polyfill.io/v2/docs/api), when describing the `features` parameter, there is the text

> though group aliases such as 'es5' and 'es6' are also accepted (these are defined in the polyfills' config.json files - [here's an example](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/from/config.json)).

and the broken link in that text should be changed to [this](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Array/from/config.json).

---
It's as if every occurrence of

*  `polyfill-service/blob/master/polyfills`

should be replaced with

* `polyfill-library/blob/master/polyfills`

in the documentation. (edited Thursday 3 January 2019)

**Comment by hultqvist** [comment]
I guess since the polyfill-library was introduced in April 9th 2018 most links to

[https://github.com/Financial-Times/polyfill-service/...](https://github.com/Financial-Times/polyfill-service/)

should be replaced by

[https://github.com/Financial-Times/polyfill-library/...](https://github.com/Financial-Times/polyfill-library/)

**Comment by JakeChampion** [comment]
This has been fixed now :-)
