### ISSUE TITLE
[Question] Why using UA instead of ability?

### ISSUE THREAD

**Issue by kud** [polyfillpolyfill/polyfill-service#1836]
Hello 👋🏻

I'm really interested by your project, and I'm thinking of adding it to my websites.

However, I've got a question. 

As we know that UA aren't reliable, that's why I wonder why don't you check the ability of a browser to load and use a method/function?

For instance, for the moment, I do this:

```
import entries from "object.entries"
if (!Object.entries) {
  entries.shim()
}
```

So I check the ability and not the UA of the browser. Which sounds more reliable in my opinion.

Thank you :)

**Comment by JakeChampion** [comment]
Hi @kud,

The reason we do not use feature detection is because that would require either:
- Sending all the requested polyfills to the browser and only applying the ones which fail feature detection, which could be a large response and have no polyfills applied if the browser has all the features already.
- Making two round-trips to the polyfill-service, once to get the feature detects and the second one to request the polyfills for the features which failed feature detection. 

UA detection is quite reliable, lots of websites are using this service and getting the benefit of our UA detection system.

You can follow issue #84 if you are wanting to know if/when we implement a simpler approach to using the service with feature detection.

**Comment by kud** [comment]
Indeed!

Thank you for your explanation. :)
