### ISSUE TITLE
No indication of default polyfills with new website/v3 service

### ISSUE THREAD

**Issue by cferdinandi** [polyfillpolyfill/polyfill-service#1861]
The website no longer mentions which polyfills are included as part of the default bundle. That makes it really difficult to reliably use the service without explicitly defining the specific polyfills to include.

**Comment by agriffis** [comment]
While we're waiting for this on the docs site, here's a way to compare the services:

```
v2='https://cdn.polyfill.io/v2/polyfill.js?features=default&unknown=polyfill'
v3='https://cdn.polyfill.io/v3/polyfill.js?features=default'
filter-features() { sed -n '/^$/q;/^ \* -/s/,.*//p' | sort; }
diff <(curl -s "$v2" | filter-features) <(curl -s "$v3" | filter-features)
```

Here's the output from the above:

```diff
18d17
<  * - Document
40d38
<  * - Number.isFinite
51d48
<  * - Object.setPrototypeOf
54d50
<  * - String.prototype.contains
62d57
<  * - Symbol.toStringTag
66d60
<  * - _ArrayIterator
68c62,96
<  * - _Iterator
---
>  * - _ESAbstract.ArrayCreate
>  * - _ESAbstract.ArraySpeciesCreate
>  * - _ESAbstract.Call
>  * - _ESAbstract.Construct
>  * - _ESAbstract.CreateDataProperty
>  * - _ESAbstract.CreateDataPropertyOrThrow
>  * - _ESAbstract.CreateIterResultObject
>  * - _ESAbstract.CreateMethodProperty
>  * - _ESAbstract.Get
>  * - _ESAbstract.GetIterator
>  * - _ESAbstract.GetMethod
>  * - _ESAbstract.GetPrototypeFromConstructor
>  * - _ESAbstract.GetV
>  * - _ESAbstract.HasProperty
>  * - _ESAbstract.IsArray
>  * - _ESAbstract.IsCallable
>  * - _ESAbstract.IsConstructor
>  * - _ESAbstract.IsRegExp
>  * - _ESAbstract.IteratorClose
>  * - _ESAbstract.IteratorComplete
>  * - _ESAbstract.IteratorNext
>  * - _ESAbstract.IteratorStep
>  * - _ESAbstract.IteratorValue
>  * - _ESAbstract.OrdinaryCreateFromConstructor
>  * - _ESAbstract.OrdinaryToPrimitive
>  * - _ESAbstract.RequireObjectCoercible
>  * - _ESAbstract.SameValueNonNumber
>  * - _ESAbstract.SameValueZero
>  * - _ESAbstract.ToBoolean
>  * - _ESAbstract.ToInteger
>  * - _ESAbstract.ToLength
>  * - _ESAbstract.ToObject
>  * - _ESAbstract.ToPrimitive
>  * - _ESAbstract.ToString
>  * - _ESAbstract.Type
70a99
>  * - document
```

Notes:

* v3 doesn't need `unknown=polyfill` because this is the main thing (I think) that changed between v2 and v3. The old policy was to ignore unknown user-agents, and the new policy is to return all polyfills by default.
* you can also use `vimdiff` in place of `diff`, it's a little easier to compare than the raw diff

**Comment by cferdinandi** [comment]
@agriffis Cool trick! Is there a way to get just a list of the defaults for v3? I'm less concerned with the differences and more interested in what's included out-of-the-box.

**Comment by agriffis** [comment]
@cferdinandi Load https://cdn.polyfill.io/v3/polyfill.js?features=default&flags=always in your browser and the list is at the top...

or change the last line of the above shell commands to:

```
curl -s "$v3" | filter-features
```

(instead of doing the diff)

**Comment by cferdinandi** [comment]
Perfect, thanks!

**Comment by azizhk** [comment]
Can we have a "Include Default Bundle" checkbox on the [URL Builder](https://polyfill.io/v3/url-builder/) page (along with Minify bundle, Real User Monitoring, Feature Detects, Always load polyfills).

Also another feature is automatically selecting checkboxes in the list based on what is requiring them. Like `(required by "default")`, `(required by "requestAnimationFrame")`. So that we don't have to include every feature if we are indirectly requiring it.

Let me know if you guys are open to this or if you know of any complications. I'll see if I can give some time and implement it.

**Comment by cferdinandi** [comment]
@azizhk I'm pretty sure the stock build is "with defaults." Unless you mean as a way to include specific non-default features + the defaults?

**Comment by azizhk** [comment]
Yup the stock build has defaults, but if you don't specify default if you are using `features` flag then defaults are not included.
https://cdn.polyfill.io/v3/polyfill.js?features=Object.entries&flags=always
So I guess I mean a way to include specific non-default features while not bundling all the defaults.
But the bigger feature is giving the user a checkbox to define whether he wants the defaults or not.

And an even bigger feature is automatically checking those boxes in the polyfill list which get covered by default or by any other feature which requires it.

**Comment by JakeChampion** [comment]
I have a work-in-progress pull-request for adding the aliases to the url-builder --> https://github.com/Financial-Times/polyfill-service/pull/1942

I'm not happy with the design but it is better than not showing them at all :-)

**Comment by JakeChampion** [comment]
https://polyfill.io/v3/url-builder/ now contains the sets/aliases and the tooltip for a specific set/alias contains the polyfills that it has.

**Comment by cferdinandi** [comment]
Thank you @JakeChampion! This looks terrific!
