### ISSUE TITLE
Integration with test262

### ISSUE THREAD

**Issue by jonathantneal** [polyfillpolyfill/polyfill-service#192]
@bterlson, how difficult might it be for a non-browser to integrate with the tests available @ https://github.com/tc39/test262 and would you know of other non-browser projects that may have had successful integrations?

**Comment by triblondon** [comment]
Having discussed this with @sideshowbarker recently, I'm fairly convinced that using test262 is not beneficial for the polyfill service.  The problem is that the aim of the 262 suite is to test complete, comprehensive feature implementation, and most polyfills fall short of that - either because of the limitations of what is technically possible or because the polyfill author hit the 80:20 barrier and thought "good enough".  A polyfill is practically useful if it sufficiently emulates the feature in the majority of use cases, and fails with reasonable grace in others.  The extent of a polyfill's adherence to the original spec of the feature can vary enormously, and I don't think it offers us any value to try and test polyfills against perfect spec compliance, particularly if that stops us from adopting practically useful polyfills or stops us serving polyfills in some browsers where they would be a big improvement over nothing at all.

Given our increasing adoption of third party polyfills, almost none of which are tested with test262, I feel that incorporating 262 into our test harness would add significantly more work and hassle than writing the tests ourselves when needed.

Will leave this open for a while for comment.

**Comment by ljharb** [comment]
Any polyfill that stops short of the limits of technical possibility is quite simply broken, and should not be used. I think it's very critical that a polyfill's adherence to the original spec _not_ vary - put another way, if it doesn't adhere to the spec tightly, it's not a polyfill, it's just a function full of lies.

**Comment by triblondon** [comment]
My interpretation of your comment is that I run a service that peddles functions full of lies.  I have spent a long time trying to respond to it, and I basically have nothing useful to say, sorry.  If you want to follow up could you do so by private email?
