### ISSUE TITLE
Surface aliases which are for a single polyfill on the url-builder, show them as polyfills rather than as aliases

### ISSUE THREAD

**Issue by niftylettuce** [polyfillpolyfill/polyfill-service#1944]

**Comment by JakeChampion** [comment]
Hi @niftylettuce, I need more information from you about this because we infact do serve that polyfill to IE/10 --> https://polyfill.io/v3/polyfill.js?features=Object.getOwnPropertySymbols&ua=ie/10

Please can you post the full polyfill.io url you are using and the full useragent of the browser you tested it in, thank you :-)

**Comment by niftylettuce** [comment]
The builder tool is not showing it @JakeChampion, here's a screenshot:

<img width="955" alt="Screen Shot 2019-03-28 at 10 52 25 AM" src="https://user-images.githubusercontent.com/523141/55172103-7fca4100-5147-11e9-9838-1d36d69593fe.png">

**Comment by JakeChampion** [comment]
Ah yes, that is true! Thank you for pointing that out, that is because it is an alias for the `Symbol` polyfill. We need to show these aliases on the page. I will rename this issue and re-open it for you.

**Comment by niftylettuce** [comment]
Bump

**Comment by niftylettuce** [comment]
I think `Map.prototype` is another example
