### ISSUE TITLE
No polyfills found for current settings

### ISSUE THREAD

**Issue by ghost** [polyfillpolyfill/polyfill-service#1977]
bug

## What
No polyfills loading

## Details

```
<!-- A clear description of what the problem or feature request is -->
/* Polyfill service v3.34.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: Array.from,Array.prototype.find,Array.prototype.includes,CustomEvent,Element.prototype.classList,Object.assign
 *  */


/* No polyfills found for current settings */
```

Used web configurator on polyfill.io

**Comment by bgronek** [comment]
I'm seeing this as well.  Unable to obtain polyfills.

**Comment by rowanmanning** [comment]
Hi @t-ricci-delta, @bgronek - are you using Google Chrome or another modern browser? Because in that case this is expected behaviour. From the home page (emphasis my own):

> ## What is Polyfill.io?
> It's a service which accepts a request for a set of browser features and returns **only the polyfills that are needed by the requesting browser**.

Could you confirm which browser you're using? If it's a browser where you'd expect polyfills to be required then we can investigate.

**Comment by rowanmanning** [comment]
Closing this, if you are still having issues then we can reopen
