### ISSUE TITLE
Can't find variable: IntersectionObserver

### ISSUE THREAD

**Issue by shang-shang95** [polyfillpolyfill/polyfill-service#1982]
Bug report

## What

I'm getting error with IntersectionObserver.
> Can't find variable: IntersectionObserver

## Details

I use script tag : `%script{src: "https://polyfill.io/v3/polyfill.js?rum=true&features=IntersectionObserver", crossorigin: "anonymous"}`
According to bugsnag, below two device causing the error: 
> browserName: Chrome
browserVersion: 61.0.3163
locale: C
osName: Windows 10.0
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 

> browserName: Chrome Mobile
browserVersion: 34.0.0
osName: Android 4.4
userAgent: Mozilla/5.0 (Linux; Android 4.4.4; SOL26 Build/23.0.C.0.296) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/34.0.0.0 Mobile Safari/537.36

**Comment by JakeChampion** [comment]
Hi @shan-shan95,

I'm not sure why you are having an error on Chrome 61 on Windows.
IntersectionObserver is configured for [Chrome 50 and below](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/IntersectionObserver/config.json#L7).

Chrome Mobile 34 does get served the polyfill and it also passes all our integration tests for the polyfill, I assume that perhaps the script either failed to download due to a network issue or perhaps there is a race condition with some other JavaScript on your website which might use IntersectionObserver before the polyfills have downloaded.

Here is a link showing Chrome Mobile 34 being served the polyfill:
https://polyfill.io/v3/polyfill.js?rum=true&features=IntersectionObserver&ua=Mozilla/5.0%20(Linux;%20Android%204.4.4;%20SOL26%20Build/23.0.C.0.296)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/34.0.0.0%20Mobile%20Safari/537.36

**Comment by shang-shang95** [comment]
@JakeChampion 
Thanks for the reply.
OK, I'll consider other causes.
