### ISSUE TITLE
Website Missing Stylesheet

### ISSUE THREAD

**Issue by benpm** [polyfillpolyfill/polyfill-service#2010]
## What

The polyfill.io website appears to be is missing it's stylesheet on some pages. Aff've found are:
- https://polyfill.io/v3/
- https://polyfill.io/v3/url-builder/
- https://polyfill.io/v3/api/

## Details

This is how the pages look on my browser (Firefox on Ubuntu):
![image](https://user-images.githubusercontent.com/10006314/62904538-0614a780-bd24-11e9-882a-199d55973817.png)

**Comment by JakeChampion** [comment]
Hi @benpm, unfortunately I can't reproduce, all the pages load with the stylesheet correctly for me. Could you try clearing your browser cache for the website and then visiting it again, maybe it was an issue local to your machine? If it still doesn't work, could you take a screenshot of the network panel in the Firefox Developer Tools please, hopefully that has some more information we can work with :-)

**Comment by white-room** [comment]
Same for me, MIME type on the stylesheet seems to be the culprit in Chrome 76 on macos.

> polyfill.io/:1 Refused to apply style from 'https://polyfill.io/v3/css.344fdf51.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by lincolnb** [comment]
I'm getting the error on chrome, edge and firefox (win 10 x64)

Chrome tools shows the error:
"Refused to apply style from 'https://polyfill.io/v3/css.344fdf51.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

Firefox is showing that css listed above as a 404.

Edit: The web server is serving the css as a 404 (with HTML mime type):

HTTP/2.0 404 Not Found
cache-control: max-age=30, public, s-maxage=31536000, stale-while-revalidate=604800, stale-if-error=604800
content-type: text/html; charset=utf-8
etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"
server-timing: HIT-CLUSTER, fastly;desc="Edge time";dur=1
request_came_from_shield: MEL
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubdomains; preload
referrer-policy: origin-when-cross-origin
timing-allow-origin: *
accept-ranges: bytes
date: Wed, 14 Aug 2019 16:03:45 GMT
age: 630546
vary: Accept-Encoding
server-timing: HIT, fastly;desc="Edge time";dur=0
content-length: 9
X-Firefox-Spdy: h2

Cheers
Lincoln

**Comment by benpm** [comment]
@JakeChampion Cleared cache, no change. Here's the error reported by the Firefox dev console:

> The resource from “https://polyfill.io/v3/css.344fdf51.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

Here's the network info:

![image](https://user-images.githubusercontent.com/10006314/63040721-463e6c00-be83-11e9-9806-d7f629ffc796.png)

**Comment by lincolnb** [comment]
@JakeChampion 

I think the issue is it is not deployed correctly in all cloud locations. When I VPN with a Europe exit point the site is fine. Which explains why you do not see the error.

The MIME error is just a product of the NotFound route and the css actually missing on certain cloud locations.

**Comment by aariacarterweir** [comment]
Seeing this too, CSS is straight up missing

**Comment by JakeChampion** [comment]
Ok, I believe I have fixed the issue, it looks like the CDN cache for the website (not the API endpoint) was out-of-sync, having the old HTML as well as the new CSS. The CSS path changes on every deployment, which is why the HTML was no longer pointing to the correct location.

A purge of the entire website from the CDN cache looks to have fixed the problem since it has removed the old HTML and is now serving the new HTML.
