### ISSUE TITLE
can i download file https://cdn.polyfill.io/v2/polyfill.min.js

### ISSUE THREAD

**Issue by t4eng** [polyfillpolyfill/polyfill-service#2051]

**Comment by JakeChampion** [comment]
@t4eng unfortunately you cannot download the file and have that work as you expect because the file changes it's content for each different browser and browser version. If you want a single file of polyfills to download you can use the flags `always` and `gated` like so -- [https://cdn.polyfill.io/v2/polyfill.min.js?flags=always,gated](https://cdn.polyfill.io/v2/polyfill.min.js?flags=always,gated).

`always` will always add the polyfills to the file, regardless of which browser has made the request.
`gated` will wrap each polyfill in an `if` statement which detects whether the polyfill should apply/execute.

I would recommend using v3 instead of v2 as the polyfills have been completely updated and have lots of the bugs in v2 fixed.

I'll be closing this issue as I believe I have answered the question but do feel free to comment on the issue if you, I will see your response and try to get back to you :-)
