### ISSUE TITLE
User-Agent deprecation and the future of polyfill-service

### ISSUE THREAD

**Issue by andrew--r** [polyfillpolyfill/polyfill-service#2244]
First of all, thanks for your work on the polyfill-service.

Google recently announced their [intent to deprecate and freeze the User-Agent string](https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ). Developers are proposed to use new [User-Agent client hints](https://wicg.github.io/ua-client-hints) in place of deprecated User-Agent. 

To my surprise, I didn’t find any discussion about the future of polyfill-service in regards to User-Agent deprecation. While initial plans to freeze User-Agent in the mid 2020 are deferred until at least 2021 due to COVID-19, it’s still going to happen sometime.

Are there any plans to support this change in polyfill-service?

**Comment by JakeChampion** [comment]
Yes, if the ua client-hints proposal does happen then we will move to use the ua client hints and fallback to user-agent for older browsers. We've been in some of the discussions around ua client hints to make sure that the proposal will work for our use-case :-) 

This has been asked in our polyfill-library repo before, I will link to that issue here -- https://github.com/Financial-Times/polyfill-library/issues/516
