### ISSUE TITLE
Bug Report: Intl polyfill on Firefox will return UTC for timezones instead of the correct one

### ISSUE THREAD

**Issue by saPhil** [polyfillpolyfill/polyfill-service#2603]
When `Intl` is included in apolyfill bundle, it will attempt to polyfill Firefox (seen in Firefox 87 and Firefox 88) unecessarily which causes things like timezone support to break. For example, when using `Intl.DateTimeFormat().resolvedOptions().timeZone`, instead of returning the user's correct timezone (like `"America/New_York"`) it will always return `"UTC"`. When `Intl` is removed from the bundle, the browser correctly retrieves the user's timezone.

It would be good if it did not try to polyfill in Firefox after version 56 as I believe that's the version that added full Intl support.

**Comment by JakeChampion** [comment]
Hi @saPhil, Intl is a big and complicated set of interlinked features, unfortunately when one feature is missing, we usually have to polyfill the entire Intl specification to add the feature.

Firefox 56 did not add all the features, for example [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#browser_compatibility) was only added in Firefox 86.

Since JS Engines do not expose the default timezone, there's currently no way for us to detect local timezone that a browser is in. Therefore, the default timezone in this polyfill is UTC. -- That's from the formatjs/intl documentation, which is the polyfill we use -- https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone

**Comment by saPhil** [comment]
Ah, I see.  And I do see now that even in the most current versions `DateTimeFormat.formatRange` and `DateTimeFormat.formatRangeToParts` aren't supported in Firefox so I guess that means it will keep being polyfilled for the forseeable future. Thank you very much for the explaination, I'll go ahead and close this issue.
