### ISSUE TITLE
Custom polyfills

### ISSUE THREAD

**Issue by monolithed** [polyfillpolyfill/polyfill-service#271]
Based on https://github.com/Financial-Times/polyfill-service/issues/180 and https://github.com/Financial-Times/polyfill-service/issues/270 I propose to add a special option for custom polyfills

``` js
getPolyfillString({
    customPolyfills: [ 'paths/to/their/location/here' ]
})
```

Something like `customTests` in [`grunt-modernizr`](https://github.com/Modernizr/grunt-modernizr)

It may be useful for such methods like [URL](https://github.com/Financial-Times/polyfill-service/pull/273), `String.prototype.at`, `Array.prototype.includes` and other methods are not present in the repository

**Comment by jonathantneal** [comment]
`Array.prototype.includes` was still using the withdrawn name `Array.prototype.contains`. I’ve filed a pull request #291. Not to interrupt your request, but thanks for the catch.

**Comment by triblondon** [comment]
It would be hard to make this part of the library API, since by the time you call `getPolyfillString`, we have already compiled all the poyfill sources into a single sources.json file.  Adding custom polyfills would need to be factored into the grunt `buildsources` task.  Currently the polyfills location is defined here:

https://github.com/Financial-Times/polyfill-service/blob/master/tasks/buildsources.js#L20

So that could be made into an array of paths, and could be passed as a grunt parameter.  Happy to accept a PR along those lines.

**Comment by triblondon** [comment]
No intent to implement this.
