### ISSUE TITLE
Is it true that polyfill.io hosting is going to be owned by a Chinese company?

### ISSUE THREAD

**Issue by hmmhmmhm** [polyfillpolyfill/polyfill-service#2834]
I recently saw a tweet from the creator of the polyfill service saying not to use polyfill.io for this project.

![image](https://github.com/polyfillpolyfill/polyfill-service/assets/38493722/ca359ae5-10f9-4eb3-a9ee-19514ce02e54)
[Twitter Link](https://twitter.com/triblondon/status/1761852117579427975)

@JakeChampion And then I read a tweet that you wrote, that you gave a company called Funnull the rights to keep it open source and to run a domain service called polyfill.io.

![image](https://github.com/polyfillpolyfill/polyfill-service/assets/38493722/dba4f089-d342-478f-afd5-0c6672028e90)
[Twitter Link](https://twitter.com/JakeDChampion/status/1761315227008643367)

I then looked up the company [Funnull](https://funnull.com/) to see what it was all about.

![image](https://github.com/polyfillpolyfill/polyfill-service/assets/38493722/93cf5883-f070-42ca-b7e4-cabf0750301e)
Funnull (方能CDN) says Made in USA on their website, but there is Chinese on the site and the main contact page is also in Chinese, and Funnull appears to represent 方能 in Chinese.

<img width="546" alt="image" src="https://github.com/polyfillpolyfill/polyfill-service/assets/38493722/81a5abd3-70f3-491a-9778-59c2f50afb4a">

I tried to access Telegram on the official website, but it's mostly in Chinese.

![image](https://github.com/polyfillpolyfill/polyfill-service/assets/38493722/c2089d6b-e66b-47ad-919d-4c0e33de094d)

And am I correct that in this project we don't give any alerts when we change the terms (why?) Am I correct that there is no obligation on the service to give any advance notice when they change the terms?

-----------

Is it really true that a project like [polyfill.io](polyfill.io), which is used by so many web services, is being taken over by a company called Funnull that seems to have some connection to China?

Based on the timing of @JakeChampion's tweet, I'm assuming the hosting has already gone over to them as of today, is this correct? What company were you referred to and are you handing over hosting rights to them, are you compensated for something?

And Andrew Betts and Jake both seem to be at the same company (Fastly right?), so can you talk a little bit about how this came to be? Apparently there are two developers in the same company, and one of them is posting about handing over hosting rights, and the other one is telling me not to use the official hosting for this project, and I can't figure out what's going on.

**Comment by munierujp** [comment]
The following is a quote from the announcement by Funnull.

>We are happy to announce that we have reached an agreement to acquire Polyfill effects on 24th February 2024. Jake Champion has decided to transfer the ownership of Polyfill to Funnull, he will no longer continue to provide the support it needs. Hosting will continue to be provided free of charge by Funnull.
Polyfill is a service that makes web development less frustrating by selectively polyfilling just what the browser needs.
We believed this acquisition would better meet our customer needs and offer a broader range of solutions.

https://funnull.com/Partner/

**Comment by zimdin12** [comment]
what will happen to the package ? This situation is quite frustrating. polyfill requests return 500.
I will move to local polyfill for now, but should I move to core-js ?

**Comment by alexmuller** [comment]
The domain `polyfill.io` is now a CNAME to `polyfill.io.bsclink.cn.` which appears to be run on [Baishan Cloud](https://intl.baishancloud.com/).

**Comment by froboy** [comment]
As per https://github.com/guardian/gateway/issues/2597#issuecomment-1967263479, `https://polyfill-fastly.io/v3/polyfill.min.js`, see https://polyfill-fastly.io/.

**Comment by henrik** [comment]
Can anyone point to something that confirms Fastly is behind https://polyfill-fastly.io? I don't see it mentioned on [their blog](https://www.fastly.com/blog) yet, for example. Would be a shame if people moved away from a suspected untrustworthy host to another.

**Comment by henrik** [comment]
To answer my own question - A records for fastly.com are 151.101.1.57 etc and A records for polyfill-fastly.io are 151.101.1.91 etc.

[According to ipinfo.io](https://ipinfo.io/AS54113/151.101.0.0/16), Fastly owns the IP range 151.101.0.0/16, which means 151.101.0.0 to 151.101.255.255. So it should be good. (But I'm not a DNS expert.)

**Comment by LeaveTheCapital** [comment]
Thanks @henrik  - came here to ask exactly the same question

**Comment by bo-rik** [comment]
Same question indeed from my side @henrik

**Comment by triblondon** [comment]
@bo-rik @LeaveTheCapital @henrik I work for Fastly.  More details about polyfill-fastly.io are here: https://community.fastly.com/t/new-options-for-polyfill-io-users/2540

**Comment by polyfillcust** [comment]
please provide full url with version that is not working, we will clear it from cdn cache.

**Comment by polyfillcust** [comment]
polyfill not managed by chinese company, by us based cdn company.

**Comment by xtuc** [comment]
Cloudflare cdnjs also launched an alternative to polyfill.io: https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk

**Comment by wesleyhales** [comment]
We gave this "event" a name (Polykill) as it brings new supply chain vulnerability considerations to light. i.e. When you include a JavaScript file on your site, who has control of the traffic and the contents of the file?
https://polykill.io/

**Comment by MattiSG** [comment]
1. We're adding Polyfill.io on @OpenTermsArchive, which will enable tracking any upcoming changes to their terms (https://github.com/OpenTermsArchive/contrib-declarations/pull/1374). You will soon be able to see the archived version on https://github.com/OpenTermsArchive/contrib-versions/Polyfill.io and to be notified of changes by [subscribing over RSS](https://github.com/OpenTermsArchive/contrib-versions/commits/main/Polyfill.io.atom).
2. This is precisely the sort of situation for which subresource integrity (SRI) was created. A simple way to protect your website and users against potential nefarious changes to the scripts being delivered consists in adding [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to your polyfill.io hot loading. SRI is basically a hash of the resource that you intend to load, provided as an attribute of the `script` you load it with. If the resource changes, the browser will fail validation and will not load the resource. One caveat is that for this to work in this context, you would have to lock the version of polyfill.io that you want to load.
3. If you're concerned not only with active script content, but also with passive resource access tracking and user fingerprinting (i.e. data being sent to suspicious datacenters from end users browsers because your app instructs them to load polyfill.io), then switching from a 🇨🇳 provider to a 🇺🇸 provider doesn't change much for your non-US users or if you're yourself as a provider not US-based. In general, relying on a third party for loading active assets is dangerous, and you should always assume that the host is actively profiling and fingerprinting users (a bit less so if it operates within GDPR 🇪🇺 jurisdiction). Protect your users, protect yourself: self-host and add SRI!

**Comment by henrik** [comment]
Would SRI work here considering that the Polyfill service [returns different responses based on the user agent](https://github.com/polyfillpolyfill/polyfill-service#polyfillio-is-a-service-which-makes-web-development-less-frustrating-by-selectively-polyfilling-just-what-the-browser-needs-polyfillio-reads-the-user-agent-header-of-each-request-and-returns-polyfills-that-are-suitable-for-the-requesting-browser)?

**Comment by SukkaW** [comment]
> The domain `polyfill.io` is now a CNAME to `polyfill.io.bsclink.cn.` which appears to be run on [Baishan Cloud](https://intl.baishancloud.com/).

Just a head up, the `polyfill.io` is not only using the Baishan Cloud:

```
$ dig polyfill.io @223.5.5.5 +short
5f52353c.u.fn03.vip.
7f5f428b.n.fnvip100.com.

$ dig polyfill.io @1.0.0.1 +short
polyfill.io.bsclink.cn.
u855.v.bsclink.cn.
```

So inside Mainland China, they are using their own CDN. And they are using Baishan Cloud in the world.

Also, the NS of `polyfill.io` has changed the DNS provider to [DNSPod](https://www.dnspod.com), which is also a China company owned by Tencent:

```
dig polyfill.io @1.0.0.1 NS +short
c.dnspod.com.
a.dnspod.com.
b.dnspod.com.
```

**Comment by Atulin** [comment]
Glad to see the JS environment is as stable as always. There hasn't been any new NPM vulnerabilities recently and I grew concerned.

**Comment by Al3676** [comment]
Oke
