### ISSUE TITLE
String.contains no longer defined

### ISSUE THREAD

**Issue by jkimbo** [polyfillpolyfill/polyfill-service#284]
Hi,

`String.contains` is no longer being defined in the polyfill bundle for chome (at least) and it is breaking our site. I'm not sure how long this has been happening for but it looks like it is related to this pr: https://github.com/Financial-Times/polyfill-service/pull/245 where `contains` got renamed to `includes`. I'm not very familiar with how the library works but it looks like `contains` should be aliased to `includes` but it doesn't appear in the current bundle (http://cdn.polyfill.io/v1/polyfill.min.js).

My solution is to pin polyfill to 1.1 until I can replace all instances of `contains` with `includes` but it would be nice if new versions didn't include backwards incompatible changes without a major version bump.

**Comment by triblondon** [comment]
Hi @jkimbo - as a rule we are happy to break backwards compatibility if a spec change happens, provided that no browser has implemented the older form of the spec.  In this case though, we are still supporting the old version, we just treat it as a separate polyfill and don't include it by default.  It would be a bit weird to include by default features that aren't actually part of the web platform specs.

To include String.prototype.contains, you just need to add it to your features list:

http://cdn.polyfill.io/v1/polyfill.js?features=default,String.prototype.contains

**Comment by jonathantneal** [comment]
Could we follow [semver](http://semver.org/)?

**Comment by jkimbo** [comment]
Following semver would be nice since this change broke production code without any changes on our part. Either that or pinning the library to a particular version should be the recommended way of using polyfill. (on that note it doesn't look like v1.2 is available? http://cdn.polyfill.io/v1/polyfill.js?libVersion=1.2)

Also Firefox has implemented `String.contains` since version 18 (https://bugzilla.mozilla.org/show_bug.cgi?id=1102219#c0) so I feel that this is a candidate for backwards compatibility.

**Comment by jkimbo** [comment]
Oh and is there a changelog published anywhere? I couldn't find one.

**Comment by jkimbo** [comment]
(Sorry for deluging you with criticism! We've just started using polyfill.io and it's pretty great!)

**Comment by triblondon** [comment]
My thoughts on this are:
- We do support .contains, we just turned it off from the default set, because it is no longer officially part of the web platform
- I think we _are_ actually following semver.  Semver is hard to apply to something like the polyfill service because it would apply to the service API, not the polyfills which are essentially _content_.  Very happy to take part in a discussion about how semver rules should be applied to the polyfill service.
- Shrink-wrapping largely mitigates library incompatibility risks, though it's great to simply be able to upgrade the web automatically, so while in an ideal world people wouldn't shrinkwrap, I think in practice many will and that's OK.
- In this case we _could_ have kept contains inside the includes polyfill as an alias, but strictly speaking that would have polluted native objects with non-standard properties.

On the libVersion 1.2, that's odd, 1.2 should be available as a symlink to `latest`, since the current release is 1.2.  Maybe something in the deploy process or the Heroku config is killing the symlink.  I've opened an issue for that: https://github.com/Financial-Times/polyfill-service/issues/285.

**Comment by jkimbo** [comment]
I understand what you are saying though I would argue that the polyfill is a library and so semver rules apply. It is creating an environment that is homogeneous across browsers and this environment should follow the same rules that browsers do, specifically not breaking backwards incompatibility. So this change should either have caused a 2.0 release or required an alias since `String.contains` was available in a perviously stable environment.

Having the main url always point to the latest version of the library still makes sense, even if that release spans a major version change, however it would be nice if there was a bigger disclaimer that this might happen and that people should use the `libVersion` parameter to ensure nothing changes underneath them. 

Oh and it is not clear from the features page that `String.contains` is not in the default set any more which might trip up some people.
