### ISSUE TITLE
polyfill-service-db

### ISSUE THREAD

**Issue by monolithed** [polyfillpolyfill/polyfill-service#303]
I propose to divide the project into two repositories `polyfill-service-db` and `polyfill-service`.

`polyfill-service-db` should use as a dependence for `polyfill-service` like:

``` js
"dependencies": {
      "polyfill-service-db": "^0.0.1"
}
```

What do you think?

**Comment by triblondon** [comment]
This has been discussed previously: https://github.com/Financial-Times/polyfill-service/issues/125

**Comment by monolithed** [comment]
Ok, I'll try to explain.

##### Can not use the `polyfill-service` as a service:

Our projects visited by tens of millions of daily users.
We can not depend on a third-party project. That is why all our content is located in own data centers.

##### Outdated package:

Prerequisites for this [issue](https://github.com/Financial-Times/polyfill-service/issues/270)
There are no the latest polyfills in the npm package (the most problem)

**Comment by triblondon** [comment]
Surely you can use the npm package as a library without running the service code?

As for the polyfills being up to date, I explained our release logic in https://github.com/Financial-Times/polyfill-service/issues/270#issuecomment-72393978, so splitting the library from the service wouldn't speed up npm releases. We'd still have to run the full compatibility suite test before making a new npm release of the library.  The only effect that splitting it up might have is to increase the frequency of _service_ releases, because it's no longer tied to the more rigorous compatibility testing process for the library.

As a solution for you, if you want bleeding edge builds of the library that have not been compatibility tested, you could just state the polyfill-service dependency in your package.json with a full github URL rather than the npm package name.

**Comment by monolithed** [comment]
> Surely you can use the npm package as a library without running the service code?

Nope, it requires some exports like `getPolyfillString`. 

>  We'd still have to run the full compatibility suite test before making a new npm release of the library. The only effect that splitting it up might have is to increase the frequency of service releases, because it's no longer tied to the more rigorous compatibility testing process for the library.

Why this problem can not be solved by versioning with `^` specifier or `shrinkwrap` file?

> You could just state the polyfill-service dependency in your package.json with a full github URL rather than the npm package name.

Unfortunately, this is not the best solution for us, because we use a local npm-repository with closed external outgoing connections (standard practice for many companies)

**Comment by triblondon** [comment]
> Nope, it requires some exports like getPolyfillString.

It has that.  Just `var polyfill = require('polyfill-service')` and the `polyfill` object exposes a `getPolyfillString` method.

I'm afraid we aren't going to split the project right now, and we don't plan to release a new version on every commit to master, but as above you're welcome to use master if you want, you'd just have to figure out how to publish it into your own npm registry.

We'll also be pushing a new release very soon, possibly this week.
