### ISSUE TITLE
Contributor agreement

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#327]
We need a contributor agreement, hopefully one to which agreement is implied by making a pull request. FT legal team can hopefully advise us - @jshalton ?

**Comment by jonathantneal** [comment]
I only ask that you honor and encourage the public domain spirit of this service, which it totally seems like you’ll be doing.

Unless I learn otherwise, I’ve also thought polyfills were inherently public domain, as they are implementations that follow [specific directions](http://www.w3.org/TR/dom/) which are [licensed public domain](https://creativecommons.org/licenses/by/3.0/).

**Comment by considermycat** [comment]
It's on my to-do list. :-) 

@jonathantneal: the main purpose of having a contributor agreement will precisely be to protect the public domain spirit of the service, e.g. by ensuring that contributors don't try to assert claims against FT or other users of the service that would threaten this. Really just a matter of making sure everyone's on the same page and has the same expectations, rather than FT making a landgrab for contributors' rights. 

@triblondon: probably a good idea to post a draft on this forum before making it final, to ensure contributors' views are heard? But that does mean I need to get on and write the thing......

**Comment by triblondon** [comment]
Thanks John. That would be great.

**Comment by triblondon** [comment]
Reopening, since #338 just added better definition around the use of third party polyfills.  We still need to add a contributor agreement.

**Comment by triblondon** [comment]
Dear @jshalton,

WITHOUT PREJUDICE

We have noted that you have agreed to provide a suggested contributors agreement for the Polyfill Service, and as yet have not done so, which is entirely reasonable.  We would refer you to the following relevant provisions:
- You might be busy;
- It may have slipped off your radar;
- It is not technically part of your job

If a contributor agreement is not provided by close of business on Friday 3rd April, we reserve the right to take further action as we see fit, which may include:
- providing inducements including but not limited to biscuits;
- sending a polite reminder;
- continuing to recognise the prevalence of higher priority work

Yours faithfully, etc.

**Comment by jonathantneal** [comment]
Dear @jshalton,

WHAT HE SAID

You’res cordially, e.g.

**Comment by considermycat** [comment]
Hi @triblondon (and @jonathantneal): mostly the first bullet point. Maybe a smidge of the second. It is definitely part of my job, though, but unfortunately (as you may have noticed...) it has not been the highest priority area of my job in the past few weeks. I will use reasonable endeavours in good faith etc etc to push it up the list "in the next period of time" (as Gordon Brown used to say). :-)

**Comment by triblondon** [comment]
@jshalton if you're happy to live without a contrib agreement I can just close this...

**Comment by JakeChampion** [comment]
This seems like it may be an important thing to work on. Do we know the current state of affairs? The website mentions the contribution terms are a work in progress and links to this issue -- https://cdn.polyfill.io/v2/docs/contributing#contribution-terms

**Comment by triblondon** [comment]
Added in https://github.com/Financial-Times/polyfill-service/commit/05188c36c993bb9093988fc109f2243f7443e683
