### ISSUE TITLE
Release governance

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#328]
I'm currently quite scared of pushing updates to the hosted service in case I break lots of websites.  We do have pretty comprehensive CI, but we probably need a bit of release governance.  I propose the following.  If we can standardise this we could probably automate more of it:
1. The release candidate is tested with the full `grunt compatgen` task to generate an updated compatibility table.
2. The commit is tagged `vX.Y.Z-rcN` where N is initially 1
3. Push to qa.polyfill.io
4. Announce the release on twitter?  Should there be a polyfill service twitter feed?
5. Wait some number of days for feedback.  If necessary, make fixes, increment N, and return to step 1
6. Update package.json version and github tag with `vX.Y.Z`
7. Publish to npm
8. Push to cdn.polyfill.io

This would allow people who are relying on the CDN service time to test new versions before they see them roll out.

Alternatively, this could be considered overlay conservative.  We offer a shrinkwrap feature, so why not be bolder about pushing updates to the CDN?

Relatedly, should releases to NPM sync perfectly with releases to the CDN?  Would it be better to make only minor releases to the CDN, but push a more frequent stream of less-well-tested patches to NPM?

**Comment by monolithed** [comment]
> Relatedly, should releases to NPM sync perfectly with releases to the CDN? Would it be better to make only minor releases to the CDN, but push a more frequent stream of less-well-tested patches to NPM?

It's more than reasonable, but what about critical patches?

**Comment by blainekasten** [comment]
So, this is a ridiculous idea, and could likely have issues I'm not thinking of. But I'm concerned that the qa.polyfill.io wouldn't get tested on the majority of websites and could still break some websites in certain cases where your tests don't engage code that other websites will.

So, my thoughts are. What if the polyfill cdn read the host of the requesting page, and if it all appears to be a local dev machine, (localhost:numbers, site.local, site.dev, other default indicators that can't represent live sites)

`/localhost:[0-9]{3,4}/.test(request.referrer)`

and, if this is safely possible, it could route these requests to the release candidates, and not the stable versions. Like i said, poke as many holes in this as possible, and call me dumb if it's dumb.

But if it's possible, I think this would guarantee a more thorough QA process as we would essentially be QA'd by anyone using the service locally. maybe there could be a flag that bypasses this process if somebody doesn't want to be part of the QA process and spend man hours on it.

Thoughts?

**Comment by matthew-andrews** [comment]
varying behaviour based on the hostname of the page including the polyfill service is a little scary.  if you spot an issue on live and then want to debug locally to figure out what's going on you wouldn't want the behaviour of the polyfill service to change…  that'd confuse me more than help me i think…

have you considered making the release batches smaller and optimising the process to minimise the overhead of making releases?  continuous delivery, an approach that many teams at the FT are independently converging on, encourages each individual feature to be released individually…  each release is smaller and therefore carries less risk.

also i would advocate decoupling the npm releases from the `cdn.polyfill.io` releases because people using packages in npm registry already have some responsibility to test the packages they're using — and upgrading a package involves a degree of manual intervention (even if that is often just hitting a rebuild button on Jenkins/Travis).
1. The release candidate is tested with the full grunt compatgen task to generate an updated compatibility table.
2. The commit is tagged vX.Y.Z-rcN where N is initially 1, which automatically spins up and deploys to qa.polyfill.io and [automatically publishes to npm](https://mattandre.ws/2015/01/npm-releasing-codeship-jenkins-travis/), this automatically create a tweet on the @polyfllio account.  (You can eliminate the update package.json step with [npm-prepublish](https://github.com/matthew-andrews/npm-prepublish))
3. Wait some number of days for feedback. If necessary, make fixes, increment N, and return to step 1
4. Push to cdn.polyfill.io

**Comment by monolithed** [comment]
@matthew-andrews 
There is no no guarantee for backward compatibility of new versions

For example, my [grunt plugin](npmjs.org/package/grunt-polyfill-service) is broken for several weeks, by reason of:

```
"polyfill-service: '^1.1.0'
```

^ — used to guarantee full backward compatibility, but polyfill-service does not!

### 1.2.0 (broken)

```
npm install polyfill-service@1.2.0
```

https://github.com/Financial-Times/polyfill-service/issues/331

### 1.3.0  (broken)

```
npm install polyfill-service@1.3.0
```

https://github.com/Financial-Times/polyfill-service/issues/339, https://github.com/Financial-Times/polyfill-service/issues/340, https://github.com/Financial-Times/polyfill-service/issues/341

1.2.0 was released a month ago!

How do you [test](https://github.com/Financial-Times/polyfill-service/issues/352)?
I'm afraid to use this project on live

For this and many other reasons, I have [proposed](https://github.com/Financial-Times/polyfill-service/issues/303) to divide the project into two.

**Comment by blainekasten** [comment]
@matthew-andrews, thanks for pointing out the flaws in my plan. It seemed to good to be true. I could definitely see things being a headache, and causing the service itself to seem unreliable in those different situations.

A potentially important question here may be, is the versioning meant for the service, or the library? A change from 1.1 -> 1.2 shouldn't break anything given semver. But I have noticed that using the library (not the service) does have breaking changes between minor versions. I think this may be sort of what @monolithed is getting to.

Otherwise, I like where things are going for this deployment plan. Do you have any way to know if when you deploy code to production if it breaks things? It might be worth doing some sort of notification to you guys when something errors out in a production world. That could be done by either wrapping the entire polyfill in a try catch and ajaxing on the catch the failure. Or you could insert a 1x1 image into the dom thats hosted on your site and compare the number of polyfill requests by the number of image requests. This might help you to manage if releases are breaking things or not and allow you to know if rolling back is a good idea.

Just droppin' two more cents.

**Comment by triblondon** [comment]
Regarding allowing for better QA, I think @blainekasten has an interesting idea.  One way it could work would be to add a query param, `prerelease=1` which would use the latest RC version of the lib if it was more recent than the latest stab;e version. This would negate the need for a QA host.  However, this assumes that the service is always stable, and the API remains identical.  Since that may not always be true I think it's safer to stick with an isolated host for QAing new rel candidates.

Regarding continuous delivery, the problem is the need for version locking.  If a user can lock to any version of the library ever released, then each release becomes slightly larger than the last, and at some point loading all possible polyfills from all released versions into memory becomes impractical.  That's why we're keeping releases a bit more periodic.

Finally, it seems we may need to think more about the choice of semver version numbers on releases that make potentially backwards incompatible changes to the polyfills.  However, I think @monolithed you need to appreciate that these breaking changes may not be intentional (the ones you highlight certainly aren't), and that following this suggested process with `rc` versions will give you the chance to verify that no accidental breaking changes have been made that disrupt your use of the library as a dependency before it is released as a stable minor version.  As a result I think this governance process should resolve your problem, do you agree?

**Comment by triblondon** [comment]
OK, I think we'll adopt this and see how it goes.  Thanks for the feedback.
