### ISSUE TITLE
Promise polyfill doesn't work in IE 11

### ISSUE THREAD

**Issue by JeffJacobson** [polyfillpolyfill/polyfill-service#360]
The promise polyfill doesn't seem to work in Internet Explorer 11. I've created a [JSFiddle sample](http://jsfiddle.net/JeffJacobson/9or49cwu/) that demonstrates this.

**Comment by monolithed** [comment]
There's no the Promise polyfill in IE11
http://cdn.polyfill.io/v1/polyfill.min.js

**Comment by callumlocke** [comment]
This is because `Promise` is not in the default set of polyfills. If a feature doesn't have a ★ icon on [this table](https://cdn.polyfill.io/v1/docs/features/), you have to ask for it.
- http://cdn.polyfill.io/v1/polyfill.js – will polyfill the default set of features (which does not include `Promise`)
- http://cdn.polyfill.io/v1/polyfill.js?features=Promise – will polyfill `Promise` (but nothing else)
- http://cdn.polyfill.io/v1/polyfill.js?features=default,Promise – will polyfill `Promise` (**in addition** to all the defaults)

Try updating your JSFiddle to load the second or third URL, and it should work in IE11.

---

NB. here's what you get when you ask for Promise...
- ...as [Chrome 41](http://cdn.polyfill.io/v1/polyfill.js?features=Promise&ua=Mozilla/5.0%20%28Macintosh;%20Intel%20Mac%20OS%20X%2010_10_2%29%20AppleWebKit/537.36%20%28KHTML,%20like%20Gecko%29%20Chrome/41.0.2272.104%20Safari/537.36) (you get nothing)
- ...as [IE11](http://cdn.polyfill.io/v1/polyfill.js?features=Promise&ua=Mozilla/5.0%20%28Windows%20NT%206.3;%20Trident/7.0;%20rv:11.0%29%20like%20Gecko) (you get a polyfill)

**Comment by JeffJacobson** [comment]
Thanks. I updated the JSFiddle as @callumlocke suggested and it works! I didn't realize that `Promise` was not a default feature.

**Comment by okonet** [comment]
I'm confused: https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Promise/config.json#L6

Also, why is Promise not a part of `es6` set?

**Comment by triblondon** [comment]
I think you're raising a point that is unrelated to the subject of this
issue. To keep things well organised, we like to deal with only one issue
per issue thread. If you think your point does relate to this issue, please
help us understand it better. Otherwise please consider raising a new issue.
