### ISSUE TITLE
Feature: search polyfill in source

### ISSUE THREAD

**Issue by alexander-akait** [polyfillpolyfill/polyfill-service#361]
Get array of string for search polyfills in source code (from detected file).

**Comment by triblondon** [comment]
@evilebottnawi I think you're asking for an ability to submit some source code and have the service figure out what features you're using.  That's a great idea but I think it works best to keep the two things separate.  First, you run a tool over your source code to figure out what features you're using, and that could then generate a polyfill service URL.

Such a tool is https://github.com/azproduction/autopolyfiller, maintained by @azproduction.  It doesn't currently use the latest version of our polyfill library, and it generates a polyfill bundle rather than a URL to the polyfill service but I think @azproduction has plans to update it at some point.
