### ISSUE TITLE
Tests are always run with the gated flag

### ISSUE THREAD

**Issue by jkimbo** [polyfillpolyfill/polyfill-service#383]
When running tests locally the gated flag is always set on the polyfill script that is loaded in the browser. This makes debugging harder since you might not actually be testing against the polyfill script in the repo but the native browser version.

I came across this issue when trying to debug https://github.com/Financial-Times/polyfill-service/pull/382 since the polyfill will throw an error in all browsers but the gated flag meant that I wasn't seeing this in Chrome because it was using the native version. 

It might be worth adding an option to the test runner to disable the gated flag?

**Comment by triblondon** [comment]
This is actually intentional, because I don't want to have to try and solve all the problems that might result from executing polyfill code in cases where the feature exists natively, resulting in some kind of potentially unholy mishmash of native and non-native functionality being inspected by the tests.

In your case, the problem was shown up by the tests, you just need to use the browser in which the problem exists.
