### ISSUE TITLE
Test-dependencies as dependencies

### ISSUE THREAD

**Issue by SimenB** [polyfillpolyfill/polyfill-service#394]
Could you move `mocha` (and possibly others?) into `devDependencies`?

**Comment by triblondon** [comment]
Not easily.  The service hosts the tests as part of the prod environment, eg.

http://cdn.polyfill.io/test/tests?feature=Promise&mode=all

Open to suggestions.  Maybe if we stick with this policy a note in the package.json would be a good idea.

**Comment by SimenB** [comment]
A quick look at your `npm scripts` told me you're using Heroku. If so, how about installing `devDeps` on Heroku?

https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process

**Comment by SimenB** [comment]
For my use case, I just want the polyfills themselves. How about moving them into it's own project, and depending on it? It'll create some overhead of course.

**Comment by triblondon** [comment]
Moving the polyfills to a separate repo has been raised several times - do a quick search of the issues to read about that, but in short, it's because the service is essentially a big test framework.

Installing devDeps when running as a service is an interesting idea, but not really the right use of it, it just makes the install size smaller for your use case (which I do appreciate is a popular one).  It would confuse anyone trying to run it as a service in production, whether on Heroku or otherwise.

You could consider excluding all our dependencies from your deploy, if you are not intending to run the Node app.  mocha is actually only 1.4MB of 123MB total dependencies.

**Comment by SimenB** [comment]
It's not an issue with deploy, as I just require the polyfills I need at build-time.

If `mocha` is the only devDep, then of course it's no real issue. I just thought someone maybe went `npm i -S mocha` instead of `npm i -D mocha`. They're right next to each other on the keyboard, so who knows :laughing:
