### ISSUE TITLE
Mandate explanations for baseline support gaps

### ISSUE THREAD

**Issue by barneycarroll** [polyfillpolyfill/polyfill-service#399]
It's frustrating to see that a particular feature won't cater for a given browser without explanation. Why can't we polyfill fetch for Safari 6? A quick Google didn't help much. Mandating an explanatory note for gaps in the baseline support matrix (and perhaps enforcing this via static analysis tests) would be nice.

Why? 
- Support gaps without explanation make me suspicious. If the developers don't feel a need to explain the limits of what they can achieve, it makes me think the code is flaky.
- Descriptions of hard limitations restore faith in the service, and inform prospective consumers that they might want to adjust their codebase.
- Perceived limitations can draw insight from developers who might see a way to improve the polyfill. In this way, the support matrix can act as a hit list for enterprising browser quirks aficionados.

**Comment by triblondon** [comment]
Normally, these gaps exist because the polyfills we are using are written by third parties that did not extend support down to our baseline.  I don't personally have the time to ensure every polyfill works down to baseline - especially as the FT's internal baseline is a lot higher than the one the polyfill service uses.  But contributions that improve polyfill compatibility in older UAs are always gratefully received - especially when they are pushed upstream first.
