### ISSUE TITLE
ImageData polyfill

### ISSUE THREAD

**Issue by dy** [polyfillpolyfill/polyfill-service#414]
Hello!
There seems to be an [`ImageData` constructor](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData), which is not supported by IE, but polyfillable via [`createImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createImageData). Contructor is times faster, but something is better than nothing.

**Comment by triblondon** [comment]
Looks fairly straightforward.  Go for it.

**Comment by triblondon** [comment]
Closing this feature request issue because it's old and there are no moves to implement this.  We would welcome this feature though, so if you are keen on seeing this in the polyfill service, head on over to the [contributor's guide](https://cdn.polyfill.io/v2/docs/contributing) for all the information you need. We are always very happy to help beginners.
