### ISSUE TITLE
Investigate why _enqueueMicrotask breaks on IE8

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#427]
Internal functions required by the polyfills should be available on all browsers. When we made this change for _enqueueMicrotask it broke on IE8 (https://github.com/Financial-Times/polyfill-service/commit/598f48770365cecfa7f0ec76f36ebca7bdfa8aef). This issue is to investigate why it breaks. For the time being we will switch the range back to IE9 and above.

**Comment by callumlocke** [comment]
I also get the `_enqueueMicrotask is not defined` error when loading from the following UA (iPad):

```
Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53
```

Happens for me with any bundle that includes `Promise`, e.g.
https://cdn.polyfill.io/v1/polyfill.js?features=default,Promise

**Comment by samgiles** [comment]
@callumlocke your particular issue is fixed in the RC (http://qa.polyfill.io/v1/polyfill.js?features=default,Promise&ua=Mozilla/5.0%20(iPad;%20CPU%20OS%207_0%20like%20Mac%20OS%20X)%20AppleWebKit/537.51.1%20(KHTML,%20like%20Gecko)%20Version/7.0%20Mobile/11A465%20Safari/9537.53)

Will be going live after the QA grace period.

**Comment by triblondon** [comment]
We no longer have an enqueuemicrotask polyfill

**Comment by jonathantneal** [comment]
Why was the _enqueueMicrotask polyfill removed? I recall some discussion about `setImmediate` not being the correct fallback. Is there an issue you can point me to to learn more about what happened?

**Comment by triblondon** [comment]
We continued to support setImmediate for compatibility, because once we have a polyfill it's hard to remove it. Also the Promise polyfill we're using piggybacks on a setImmediate implementation, so we were previously having to modify the polyfill to hook it up to enqueueMicrotask.  Just using setImmediate means we can modify the polyfill less.
