### ISSUE TITLE
Add "exclude" config option

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#435]
There is an `|always` flag to make sure the bundle always contains a given feature regardless of the UA string. I think there should also be a `|never` flag for preventing a given feature being polyfilled when it usually would be.

Use case:
- I've already polyfilled `window.Promise` using Bluebird (because I'm already using it in my application code, so why not use it as my global Promise polyfill).
- I want to use the polyfill service to load the `default` set and `fetch`
- ...but loading `fetch` will cause the polyfill service to include `Promise` in the bundle - overwriting my own copy, or at least wasting bandwidth.
- so it would be nice if I could do `?features=default,fetch,Promise|never`

**Comment by triblondon** [comment]
I'm wondering if a `never` modifier is the right semantic flag for this, or whether it would be better to have an `exclude` parameter, so the URL would be more like:

`?features=default,fetch&exclude=Promise`

What do you think? @callumlocke

**Comment by callumlocke** [comment]
I agree that makes more sense.

**Comment by lewisje** [comment]
I just discovered this service, and it would be great to exclude just `Intl` because that polyfill is almost 17MB, even minified (probably to set all of the specific locale information).

**Comment by triblondon** [comment]
You don't need to specifically exclude intl because it's not included by
default anyway (precisely because it's large). The features page of the
website has a star against all the default features.

**Comment by lewisje** [comment]
The idea is that I'd like to include _everything but_ `Intl` and there's no obvious way to do that, other than enumerating every package that doesn't have `Intl` in it.

**Comment by triblondon** [comment]
Including all features is generally a bad idea.  We could at any moment ship another 17MB polyfill and because you only excluded intl, you'll get the new huge one.  I do think Callum's use case is reasonable, but I'm not going to get to this right now.

**Comment by lewisje** [comment]
I'm not entirely familiar with how all of the packages are named and I have not seen documentation on all of the package names (apart from a comment in the unminified JS that states which packages require each polyfill, from which a comprehensive list of packages could potentially be generated), but it really doesn't look like I could just specify all the top-level objects I wanted polyfills for and have that work, nor is there any other way to enumerate all the polyfills that currently exist and to except particular ones (mostly because so many of the polyfills are required only by the `all` package and do not appear to be selectable other than by selecting `all`).

For now I'm just using `es5,es6,es7,html5shiv`, all gated, because of an issue with one of the polyfills in the `default` package that throws in IE8 (which may have been mentioned in another issue posted here), but that excludes most of the useful DOM-based polyfills.

**Comment by triblondon** [comment]
> it really doesn't look like I could just specify all the top-level objects I wanted polyfills for

Why not?  You can do `?features=Array.prototype.forEach,document.querySelector,navigator.geoLocation` etc.  Just list all the features you want.
