### ISSUE TITLE
Polyfill thrashes CPU

### ISSUE THREAD

**Issue by slightlyoff** [polyfillpolyfill/polyfill-service#452]
See: https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element/polyfill-ie7.js#L90

This was observed to be spamming the render process in Chrome; it's a bit strange that this code doesn't at least check for Promises or rAF to do that better.

/cc @triblondon

**Comment by triblondon** [comment]
Thanks, clearly this is a far too aggressive implementation, and we'll update it.

I'm curious about why this was seen in chrome. The default behaviour of the polyfill service is to vary output by user agent, and chrome would not receive this polyfill (because it doesn't need it).

Do you know the cdn.polyfill.io URL of the script resource that served this code to chrome? It's also important to know whether the URL contains a `libVersion` argument, because if it does a release on our part will not solve the problem for site developers who have chosen to lock their library version.

**Comment by triblondon** [comment]
@slightlyoff the reason it doesn't try using raf or Promises is that neither of those technologies exist in IE7, which this code is designed to run in.  It's even classified as a UA-specific implementation, so the only reason you'd see this in chrome is if the developer overrode the default UA detection or the end user was spoofing an IE7 UA in Chrome.

For example, this script URL would load that code unconditionally:

```
https://cdn.polyfill.io/v1/polyfill.js?features=Element&ua=ie/7
```

IE7 is unsupported by the FT.  This polyfill came from an original implementation by @jonathantneal but it looks like I refactored it a bit some time ago.  I've proposed in https://github.com/Financial-Times/polyfill-service/issues/456 to drop a load of browsers from the service, but in the meantime I'll increase the timeout and add a limit to the number of iterations.

**Comment by triblondon** [comment]
OK, seems I let Alex up the garden path a bit on this - the problem is not in the Element constructor polyfill, though the change there is sensible, but in _enqueueMicrotask.

**Comment by triblondon** [comment]
Looks like the enqueueMicrotask polyfill was replaced by a better implementation in a recent release of the service, but the library that the Next FT site is using is locked to a previous version of the code.  I've nudged the Next team to update their dependencies, mitigated the effect of the remaining tight setInterval loop, and am tracking the idea of removing it in #456.

**Comment by JakeChampion** [comment]
Next FT seem to be specifying _enqueueMicrotask with the always flag, this may be why Chrome got the polyfill.

https://github.com/Financial-Times/next-js-setup/blob/30d4c5ad506b6b7b3b7be014246c94f7a7832ceb/templates/js-snippets/polyfills-url.html#L1
