### ISSUE TITLE
iOS Intl polyfill problem

### ISSUE THREAD

**Issue by eek** [polyfillpolyfill/polyfill-service#470]
Intl pollyfill doesn't work on mobile Safari nor Safari on iPads

Example of User Agents:

`Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H141 Safari/600.1.4`
&
`Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53`

**Comment by triblondon** [comment]
Thanks for the bug report.  Can you help us out with:
- what is the symptom of the problem?
- do our tests pass? (/test/tests?feature=Intl)
- are there any errors reported to the console?
- can you provide the CDN URL you are using to test?

**Comment by JakeChampion** [comment]
@eek 
Both of the given UA strings get the Intl polyfill when requested.

Would you be able to comment on this issue with the information @triblondon has requested? Once we have that information we should be able to help with your issue.

**Comment by shivjm** [comment]
I just ran into the same issue using Mobile Safari 9 on iOS 9.2.  When I try this:

``` javascript
var formatter = new Intl.NumberFormat()
```

I see this error in the console:

> ReferenceError: Can't find variable: Intl

The [tests page](http://cdn.polyfill.io/test/tests?feature=Intl) only says it ‘has testing suite’ and ‘has feature detection’.  Both these tests pass.

The script URL is: https://cdn.polyfill.io/v2/polyfill.min.js

**Comment by triblondon** [comment]
@shivjm can we have the UA string of the device you are testing in?

**Comment by shivjm** [comment]
`Mozilla/5.0 (iPhone; CPU iPhone OS_9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1`

**Comment by JakeChampion** [comment]
The script url you posted does not include Intl in the features array. The Intl polyfill team have documentation on how to use Intl and the Polyfill-service - 
https://github.com/andyearnshaw/Intl.js#intljs-and-ft-polyfill-service

The reason the tests page only has 'has testing suite' and 'has feature detection' is because the canonical polyfill lives in a different repository.

To check that a polyfill is served to your UA, you can pass the UA string as a query parameter - this url will check for Intl and the english locale with the UA you posted -
 https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en&ua=Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS_9_2_1%20like%20Mac%20OS%20X)%20AppleWebKit/601.1.46%20(KHTML,%20like%20Gecko)%20Version/9.0%20Mobile/13D15%20Safari/601.1

**Comment by shivjm** [comment]
Alright, thank you.  I missed that the Intl polyfill was not included by default (in fact, I missed the fact that there was a default set at all, heh).  It seems fine now.

**Comment by shivjm** [comment]
Alright, thank you.  I missed that the Intl polyfill was not included by default (in fact, I missed the fact that there was a default set at all, heh).  It seems fine now.

**Comment by JakeChampion** [comment]
Pinging @eek, was your problem the same as @shivjm's? If so, we can close this issue. If it is not the same, could you respond with this information:

> What is the symptom of the problem?
> Do our tests pass? (/test/tests?feature=Intl)
> Are there any errors reported to the console?
> Can you provide the CDN URL you are using to test?

**Comment by eek** [comment]
@JakeChampion, yeah, I wasn't using with the `?features=Intl.~locale.en`
