### ISSUE TITLE
edge mobile is ie mobile?

### ISSUE THREAD

**Issue by craigbilner** [polyfillpolyfill/polyfill-service#564]
Should edge mobile alias to ie_mob? There doesn't appear to be any obvious docs on the support but for now would it be better to assume ie_mob rather than unsupported?

**Comment by triblondon** [comment]
I didn't realise Edge has a different UA on mobile.  But it probably uses the same rendering engine as Edge desktop, right? (hopes)...

**Comment by craigbilner** [comment]
@triblondon,

so the docs seem a bit scant and I'm guessing not because it doesn't support fetch? (which is what brought me here...)

This is the UA I get on the MS VM.

"Mozilla/5.0 (Windows Phone 10.0;  Android 4.2.1; Nokia; Lumia 520) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Mobile Safari/537.36 Edge/12.10130"

**Comment by triblondon** [comment]
OK, so currently that UA is being parsed as `edge mobile/12`, which is a great start.  I think we need a bit of expert help here.  Is @jacobrossi in the house?

My instinct is that Edge mobile must be a closer match for Edge desktop than IE mobile, but I would really hate to have to create a separate set of polyfill targeting for it, so hopefully either IE mobile or desktop is close enough?

Jacob - it'd actually be super helpful if you could help us with Edge versioning in general.  I believe your official version number is currently 20 but your UA string says 12 and we refer to Edge as `ie/12` right now.

**Comment by jacobrossi** [comment]
Edge on mobile uses the exact same engine as Edge on desktop.  When the user has "Request Mobile sites" enabled (the default), then the UA string contains a "Mobile" keyword as you've noticed as well as it saying "Windows Phone" instead of "Windows NT" and also the name of the device.

Desktop UA:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.11082`

Mobile UA:
`Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 950 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586`

Feature support is almost entirely the same across both mobile/desktop (see [status roadmap](http://status.microsoftedge.com) for the general list). However, there are a few exceptions.  

Most differences between EdgeHTML on mobile and on desktop are similar to any other mobile browser:
- No Flash
- meta viewport is supported
- content is shrink-to-fit if no viewport is specified
- Touch Events enabled

IIRC there may not be EME support on mobile, but I'd have to check on that to be sure. Additionally, I don't believe ORTC is supported on mobile yet.

For more docs: [Edge Developer Guide](https://msdn.microsoft.com/library/dn904191.aspx)

Edge has two version numbers. One describes the app, the other describes the rendering engine. So you really care about the latter.  Version 12 came out this summer (the first release), Version 13 came out in November.  Preview builds of 14 will be out soonish I imagine. Only the rendering engine version number is included in the UA String because that's what matters to sites.

**Comment by triblondon** [comment]
Cheers Jacob!  If you have a UA for v13 to hand that would be very helpful.

@craigbilner TLDR here is that we should alias `edge mobile` to `ie` in the UA module, which is what we're calling Edge for simplicity (and because helpfully it's first release version is v12, while the last release of IE is 11)

**Comment by jacobrossi** [comment]
FWIW I'm not sure what the impact of your UA module is, but worth noting the EdgeHTML platform is far closer to Blink than it is to IE these days. Last count I made (as of v13 I think), 977 APIs removed and 1192 added compared with IE.

v12 UA:
Mozilla/5.0 (Windows NT 10.0;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

v13 UA: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

v14 will follow the same pattern:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/XXX.XX (KHTML, like Gecko) Chrome/YY.Y.YYYY.Y Safari/XXX.XX Edge/VV.BBBBB

Where X is a recent stable Safari version number as of the **stable** release of that EdgeHTML version, Y is a recent stable Chrome version number, V is the EdgeHTML version number (12, 13, 14...), and B is the build number of that EdgeHTML release. The Chrome/Safari version numbers are generally selected based on compatibility data we get from preview build users.

**Comment by craigbilner** [comment]
@triblondon @jacobrossi thanks, really helpful stuff

**Comment by triblondon** [comment]
Superb, thanks Jacob.  I appreciate that Edge is not the same animal as IE, we just have a considerable admin overhead in defining a new browser family, so we are taking a shortcut here by assuming that IE will never have another release, and typically an IE11 user's upgrade path takes them to Edge.  We test compatibility, so lumping them in the same family has no impact on the polyfills we serve for them.

@craigbilner would you care to make a PR here?

**Comment by craigbilner** [comment]
@triblondon, done, let me know if you need anything else, looks like there's a CI problem at the moment though...

**Comment by triblondon** [comment]
#571
