### ISSUE TITLE
`unknown` param no longer working in `v2`

### ISSUE THREAD

**Issue by callumj** [polyfillpolyfill/polyfill-service#572]
Some `UIWebView`s on iOS don't report decent user agents so we are using `unknown` as a fallback, but it seems to no longer be working:

```
» http GET "https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill&features=es6,Intl.~locale.en|always"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 37
Cache-Control: public, max-age=604800, stale-while-revalidate=604800, stale-if-error=604800
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 63
Content-Type: application/javascript; charset=utf-8
Date: Mon, 11 Jan 2016 20:07:36 GMT
Etag: W/"2d-o7gMCX6akln1e+RqzU7W9w"
Server: Cowboy
Timing-Allow-Origin: *
Vary: Accept-Encoding
Vary: User-Agent
Via: 1.1 vegur
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Served-By: cache-lax1428-LAX
X-Timer: S1452542856.430777,VS0,VE0

/* Unsupported UA detected: httpie/0.9.2 */
```

**Comment by callumj** [comment]
A real life example is the `UIWebView` in the Facebook iOS app:

```
/* Unsupported UA detected: facebook/5.3.0 */
```

**Comment by triblondon** [comment]
I don't think that's new behaviour, I think it's because in a recent release we updated our copy of the useragent library and it's now able to recognise more weird and wonderful UAs.  We've never actually applied the `unknown` policy if the browser is known but unsupported.  This seems like a weird policy in retrospect, so I'm going to change that behaviour to treat all unsupported browser families as 'unknown'.

**Comment by callumj** [comment]
Are you able to `PURGE` the cache for existing requests, looks like it is cached for some UAs.
