### ISSUE TITLE
Easy debugging utility for mobile

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#575]
For browsers that don't offer access to dev tools, and where even entering a url in the nav bar can be painfully difficult i.e. older mobiles, it'd be useful to have a tiny debugging utility allowing info about polyfills to be output on the page

Something like `https://my-site.com/buggy-page?polyfill-service-info=alert` (or `=console`) would turn on the following:
- before polyfills are installed alert that the polyfill script is beginning to run
- after they have loaded alert which polyfills were available, and which have been installed

**Comment by JakeChampion** [comment]
The steps I use to debug such browsers:
Find the user agent 
Copy the polyfill-service url, remove the `.min` if present and add the user agent as a query parameter `&ua=xxxxxxx`

I think your approach may be less steps but not as useful because the debugging happens on the device itself whereas the approach I've described can happen on any device.

**Comment by triblondon** [comment]
This requires the polyfill service to have a runtime, ie code that we always ship in addition to the polyfills themselves.  I'm very reluctant to do this because it feels like the thin end of the wedge. I think as Jake says there are already a decent number of options here.
