### ISSUE TITLE
IE8 keeps elements hidden, when el.hidden = false;

### ISSUE THREAD

**Issue by thisconnect** [polyfillpolyfill/polyfill-service#580]
Hi
https://github.com/necolas/normalize.css/pull/497#issuecomment-174136431

**Comment by triblondon** [comment]
Looking at @jonathantneal's comment [here](https://github.com/necolas/normalize.css/pull/497#issuecomment-174136431) I'm wondering why this is a bug. If boolean attributes are not allowed to have values, and so a value of false is equivalent to true (because it's the presence of the key rather than anything to do with the value), hiding an element when it has a `hidden` property would be correct behaviour, no?

**Comment by thisconnect** [comment]
Hm.. The behavior of all other browsers is that they remove the hidden attribute on `el.hidden = false;`

**Comment by triblondon** [comment]
Ah, I see.  OK, in that case a PR with @jonathantneal's solution would be welcome.

**Comment by JakeChampion** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is moderately appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor. We would need to ensure that the polyfill is filling for a standard feature of the web platform, which we're not sure is the case here.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!
