### ISSUE TITLE
Support data for URL is wrong

### ISSUE THREAD

**Issue by DavidBruant** [polyfillpolyfill/polyfill-service#640]
[The doc](http://cdn.polyfill.io/v2/docs/features/#URL) suggests that Firefox does not support it while it has for some time and does now https://developer.mozilla.org/en-US/docs/Web/API/URL#Browser_compatibility
Same for Chrome which supports it since Chrome 32 apparently.

**Comment by triblondon** [comment]
In fact our docs show polyfillable in Chrome, missing in FF:

![image](https://cloud.githubusercontent.com/assets/1735391/13869577/8b28d3ee-ed19-11e5-8c94-ef51ecb944c9.png)

Chrome makes sense. It has only fully supported URL since 49, which we are not yet showing on our compat table.  Firefox claims full support since 29, but is failing one of our tests on its native implementation:

![image](https://cloud.githubusercontent.com/assets/1735391/13869608/cff9cef6-ed19-11e5-9550-a7d8fed4f938.png)

So we could skip this test, on the basis that the bug is not important enough to stop us showing the native support exists.

**Comment by gheoan** [comment]
@triblondon To be clear, the docs show `Feature missing` instead of `Feature supported natively` in FF because of that failing test?

**Comment by triblondon** [comment]
Yes

**Comment by DavidBruant** [comment]
Just for info, in the Firefox 47 (dev edition) console:

``` js
var url = new URL('http://example.com');

url.searchParams.append('this\x00&that\x7f\xff', '1+2=3');

console.log(url.search === '?this%00%26that%7F%C3%BF=1%2B2%3D3');
console.log(url.href === 'http://example.com/?this%00%26that%7F%C3%BF=1%2B2%3D3');
```

both yield `true`, so I guess the tests started passing sometimes between FF39 and FF47.

Anyway, thanks for addressing this!

**Comment by triblondon** [comment]
@DavidBruant we have data for FF41 so it's somewhere between 42 and 47.

As a footnote to this, an alternative solution is to add this test to the detect.js file, which makes passing this test part of the definition of whether the feature is present or not. That would mean that we would serve the polyfill to FF < ~47, on the basis that the native impl is not detectable. However, it's a judgement call, and I take the view that it unnecessary to polyfill a feature that has a native implementation which for most use cases is not broken.
