### ISSUE TITLE
Feature request: Ability to pin feature versions

### ISSUE THREAD

**Issue by jimf** [polyfillpolyfill/polyfill-service#650]
I experienced what was effectively a site outage for Safari users due to the inclusion/release of Intl v1.1.0. I'd love to have the ability to pin feature versions so updates can go through a QA process rather than being automatic.

**Comment by triblondon** [comment]
Hi Jim.  We did previously have that feature, and it was removed because it completely decimated both our cache perf, and also our ability to push releases cheaply.  However, we do have a QA site at qa.polyfill.io and we commit to pushing to `qa` at least seven days before we push to `cdn`.  This is intended to give site authors like yourself the opportunity to test your sites before the release.

As an alternative you can obviously run your own version of the service and then you can stick with whichever version you like.

**Comment by jimf** [comment]
Ah, this is great, thanks for the info. Aside from watching the GitHub repo, are there any alternatives (ideally push-based) for being notified of changes coming down the pipeline?

**Comment by triblondon** [comment]
There are now!  Follow @polyfillio on twitter.

**Comment by jimf** [comment]
:beers:
