### ISSUE TITLE
Promise polyfill is not exported to 'window' if CommonJS is used 

### ISSUE THREAD

**Issue by everyonesdesign** [polyfillpolyfill/polyfill-service#662]
This piece of code in Promise polyfill makes the whole polyfill file export the Promise object and prevents its export to window if CommonJS modules are used: 

```
    if (typeof module != 'undefined' && module.exports) {
        module.exports = global.Promise || Promise;
    } else if (!global.Promise) {
        global.Promise = Promise;
    }
```

That looks strange, I think polyfill should always export it to window as it imitates native behavior.

**Comment by triblondon** [comment]
This is a fairly common approach to making code with multiple module system compatibility. In the polyfill service it is ineffective and will always export the API to `Promise` on the global object, because there is no `module.exports` in the browser.

We prefer to retain polyfill source as originally written if it is not causing a problem, since it makes it easier for us to update.
