### ISSUE TITLE
Detecting failed loading

### ISSUE THREAD

**Issue by ashleynolan** [polyfillpolyfill/polyfill-service#664]
First up – great work on providing this service.  Insanely useful! :dart: 

I’ve got more of a question than an issue relating to providing a fallback for the service.  The uptime stats are really impressive, but is there some kind of check that can be made so that should the polyfill service not respond for whatever reason a fallback JS file could be loaded in as a replacement?  Not sure if I’m missing some crazily easy way of doing this, but as there’s no specific polyfill object returned, I’m not sure what to check for the presence of to see if it’s successfully loaded.

I guess the way I’d like to implement it would be so that in the event of the CDN ever going down – for whatever reason – then having a failsafe bunch of fallbacks being loaded in locally, rather than my site falling over without the needed polyfills.

Would be interested to know how you recommend handling this to mitigate against any potential downtime.

Thanks!

**Comment by triblondon** [comment]
Hi Ashley!

You probably want something like this:

``` html
<script src="https://cdn.polyfill.io/v2/..." onerror="loadFallback()"></script>
```

You should really attach the event handler via `addEventListener`, and also bear in mind that slow responses rather than immediate failures will not invoke your fallback until you hit the browser timeout which is probably 30-60s.

I'm on a phone so I haven't tested this but let us know if it works and helps you out, or if you find some other solution.

**Comment by ashleynolan** [comment]
Ok, will take a look at implementing something along those lines and let you know how I get on.  Thanks :+1:
