### ISSUE TITLE
classList polyfill not working

### ISSUE THREAD

**Issue by onishiweb** [polyfillpolyfill/polyfill-service#678]
`domTokenList` constructor throws an error on native. (@JakeChampion knows what that means).

**Comment by triblondon** [comment]
@onishiweb can you describe the symptom a bit more?  I'm aware that DOMTokenList is a private constructor, and we can't replicate that so the polyfilled version is public.  How is that proving to be a problem?

**Comment by JakeChampion** [comment]
It was spotted on some flaky tests in o-tabs I believe.

This is the error being thrown and how the error is being thrown:

``` js
new DOMTokenList
Uncaught TypeError: Illegal constructor(…)
```

**Comment by triblondon** [comment]
That code will indeed throw on native implementations of DOMTokenList.  Are we causing that behaviour somewhere though?  We should be serving DTL polyfill whenever we serve the CL one, making the constructor public.

**Comment by triblondon** [comment]
OK, this is happening when we load the service in a browser that supports DOMTokenList natively and which either does not support classlist, or (more likely) where we are loading the classlist polyfill without the gated flag.  Classlist polyfill cannot use a native DTL because the spec says the constructor is private.

Options:
- bring the DTL functionality into CL and consider it part of the same polyfill.  Not great since DTL is used by other APIs too (although none that we have polyfills for)
- create a private polyfill that creates a guaranteed-public DTL constructor that polyfills can use (probably the best option)
- Put a mandatory feature detect into classList polyfill, so we don't try to polyfill it if it already exists (easiest - one line change - and probably avoids the problem but does not technically fix it)

**Comment by triblondon** [comment]
OK, I went with the second solution.  See branch `domtokenlist-fix`.

**Comment by triblondon** [comment]
See https://github.com/Financial-Times/polyfill-service/pull/693

**Comment by mridgway** [comment]
This issue was re-introduced by https://github.com/Financial-Times/polyfill-service/pull/1347
