### ISSUE TITLE
Access specific hosted versions ?

### ISSUE THREAD

**Issue by joaojeronimo** [polyfillpolyfill/polyfill-service#716]
I was also affected by https://github.com/Financial-Times/polyfill-service/issues/715 and that got me thinking, if only there was a way to use the polyfill service as you use a dependency with a fixed version... It wouldn't break my code unexpectedly, and I would be able test it properly before I upgrade, just like I do with dependencies.

In fact if you think about it, it doesn't sound like a very good idea to be in production relying on a service that generates a bundle that can be changed at anytime without you being able to test it on a staging environment and make sure all devices are ok.

So is there away to access a specific version of the polyfill service ? Something like `https://cdn.polyfill.io/v2/polyfill.v3.6.0.min.js` or, why is `v2` there anyway, and why not make it `https://cdn.polyfill.io/v3.6.0/polyfill.min.js` ? Not sure if it's possible but seems elegant.

The only alternative for this I see currently is installing a specific version of polyfill-service like `npm install --save-dev --save-exact polyfill-service@3.5`, then on every request pass down the user agent do a service on my end, and generate a bundle based on that.

**Comment by JakeChampion** [comment]
We publish to http://qa.polyfill.io 7 days before publishing to http://cdn.polyfill.io. That should be what your staging environment uses, you can also track releases via Twitter or Github for when we release to QA for testing.

We used to have legacy polyfills, it was removed as it was not used and added complexity to the codebase -- https://github.com/Financial-Times/polyfill-service/pull/560/commits/66385a12200c9671b21e5d818b7fa9cfdd3e57f5

**Comment by joaojeronimo** [comment]
Publishing to QA is great but introduces hard deadlines to test the changes and adapt on a team using polyfill service every time there is an upgrade.

I will spike something to do with subpaths a bit later, perhaps useful for this case.

**Comment by triblondon** [comment]
We removed this feature because it was actually preventing us from pushing bugfixes. Every time we pushed to prod, we had to bundle yet another complete copy of the polyfill collection. Since the app reads the collection into memory for fast performance, this meant rampant increases in memory consumption over time.

If you want the reliability of something you'd update on demand using a build tool, you really should be running your own version of the service.

However, this does make me think that there's potentially another solution: we could define fixed default collections. These problems have happened because we changed what's in the default collection. If we created a new alias `default-3.5` and tagged all the polyfills that were previously default, and also `default-3.7` on all the polyfills that have `default`, then you can choose to evolve with the collection, or stick to the set that was in the default collection when you first started using the service.

You would still be subject to changes in polyfill targeting and bugfixes in the polyfills themselves but this is considerably lower risk than gaining new polyfills that you hadn't previously tested with your site.

What do you think?

**Comment by joaojeronimo** [comment]
When you say update on demand using a build tool, do you mean installing this module as a dependency and generating polyfills at runtime, i.e. running a specific version of the polyfill service myself ? Yes that is a viable solution.

I think releasing a versioned default bundle is a great idea, but I don't see how someone would be subject to bugfix changes as those would be different versions if you follow semver.

**Comment by triblondon** [comment]
> When you say update on demand using a build tool, do you mean installing this module as a dependency and generating polyfills at runtime, i.e. running a specific version of the polyfill service myself ? Yes that is a viable solution.

Yes - either run it as a dependency and use it as a library via the Node API, or run it as an independent SaaS platform like we do, but just for your benefit.

> I think releasing a versioned default bundle is a great idea, but I don't see how someone would be subject to bugfix changes as those would be different versions if you follow semver.

`/polyfill.min.js?features=default-3.5` would be the same set of features forever.  Those features' polyfills might change, however.  If any changes are released to their polyfill.js files, those changes will be reflected in the response you see.  However if we choose to change what features are included by default, you don't get that change if you are using one of these theoretical 'frozen' alias names.

I think it's a pretty decent compromise actually. @JakeChampion what do you think?

**Comment by joaojeronimo** [comment]
But if you are going to change anything, that's a new version altogether right ? You start with `default-3.5.0`, then you release a couple of bugfixes with `default-3.5.1` and so on, that wouldn't break anyone.

**Comment by RyKilleen** [comment]
At some point on a client's website, we also started experiencing trouble at an undetermined time, though my hunch is after #666 ( 😈 )

While I appreciate that this is a free service and a wonderful asset, this client does not pay enough to keep up-to-date with a polyfill service. A versioned set of defaults would be extremely useful to us, as it is difficult to even isolate the issue/change and troubleshoot without spinning up our own service. 

Also, thanks for all the hard work put into a super useful tool.

**Comment by triblondon** [comment]
Implemented immutable set definitions in #725

**Comment by RyKilleen** [comment]
@triblondon Thanks a ton, really appreciate the work!
