### ISSUE TITLE
Fetch polyfill not working in IE8

### ISSUE THREAD

**Issue by henriknorberg** [polyfillpolyfill/polyfill-service#732]
Github have stopped supporting IE8 and IE9, but there is a fork that is getting updated here: https://github.com/camsong/fetch-ie8

**Comment by jhiswin** [comment]
The fork just polyfills a couple things that fetch depends on like Promise, right?
Since those polyfills already exist in polyfill-service, you can just have those as fetch dependencies.

**Comment by triblondon** [comment]
There's an update to the latest fetch here: https://github.com/Financial-Times/polyfill-service/pull/728.  It is currently failing in older IE, but I think this is because of a problem with some of our dependency polyfills, on which it now depends.  It's on my list to look at, but right now we're using a version of the polyfill that still has IE8 and 9 compatibility, and we won't likely merge the update until we achieve passes in those browsers.
