### ISSUE TITLE
SECURITY WARNING: Concerned about registry changes in shrinkwrap

### ISSUE THREAD

**Issue by tracker1** [polyfillpolyfill/polyfill-service#734]
I'm concerned about the changes (https://github.com/Financial-Times/polyfill-service/commit/d6961c57aaed6c83884c8718c5cd97185516840a) in the shrinkwrap file that are not pointing to the official npm repo, or to github.

I'm not familiar with `npm.n8s.jp` and frankly it makes me a little uncomfortable.  I would suggest a security audit of the packages in question if these are in fact the same hash as official, and if different then do an unpublish of any affected releases.

**Comment by triblondon** [comment]
Thanks for this. I'm extremely glad that you caught it and vey much appreciate it. It's happened because I am currently working on a project with some private packages that use that registry and my ~/.npmrc has gotten updated with this registry address. I will push a correction shortly.

That said I don't believe this change is a security issue since my organisation controls this registry, but it's a bad mistake that we'll fix imminently!

**Comment by tracker1** [comment]
Okay, it was just an alarming sight, as I had no familiarity with with the registry in question, just following the repo, and noticed the changes...  Just wouldn't want people to get potentially injected scripts.

**Comment by triblondon** [comment]
Fixed in https://github.com/Financial-Times/polyfill-service/commit/eb04e02c38acc6b7bf1c095b14a1ab68e35de857
