### ISSUE TITLE
Add support for Vivaldi

### ISSUE THREAD

**Issue by zchrykng** [polyfillpolyfill/polyfill-service#735]
I am guessing that all this needs is a user agent alias.

**Comment by triblondon** [comment]
Aliases are in https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js

**Comment by triblondon** [comment]
I've raised this with the Vivaldi browser folks:
https://twitter.com/triblondon/status/819198359986544640

**Comment by nifgraup** [comment]
Vivaldi has a UA scheme where Vivaldi

**Comment by nifgraup** [comment]
Vivaldi has the same UA as Chrome + Vivaldi specific added at the end. Currently it is

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.98 Safari/537.36 Vivaldi/1.6.689.46`

**Comment by triblondon** [comment]
@nifgraup thanks.  If I test that UA we already recognise it specifically as vivaldi:

https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(X11;%20Linux%20x86_64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/55.0.2883.98%20Safari/537.36%20Vivaldi/1.6.689.46

The problem is we have no polyfills for vivaldi. I could alias it to chrome but it has a different version scheme so we'd need to map each version.  Would the best solution be to remove the `vivaldi/n.n.n` token from the UA before parsing?

If I do that, the UA above gets picked up as chrome 55:

https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(X11;%20Linux%20x86_64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/55.0.2883.98%20Safari/537.36

Is that good enough for polyfill purposes?

**Comment by nifgraup** [comment]
Yes, that is good enough. Keep it simple.

**Comment by nifgraup** [comment]
I notice that Vivaldi is not capitalized in the regex.

**Comment by JakeChampion** [comment]
@nifgraup The regex is using case-insensitive matching
