### ISSUE TITLE
Abbreviating native properties

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#763]
I see a fair few polyfills doing this kind of thing:

```
var gOPN = Object.getOwnPropertyNames;
```

Is there a benefit to this? I feel it generally makes polyfills harder to read, and although it makes the code shorter, that should probably not be an objective for non-minified code anyway.  I wonder if the issue is that minification cannot reduce the length of the native property but can if you reassign it to a private variable.  But in that case maybe it should be called `getOwnPropertyNames`?

I'm not suggesting we change anyone else's polyfills but we have authoring guidelines and I'm wondering if this is worth mentioning there.

**Comment by JakeChampion** [comment]
I'll explain that specific snippet which is from the [Symbol polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/polyfill.js#L18).

We can definitely give the variable a more verbose name.

The benefit to assignment is that we have a reference to the native method which is required because we need to modify this method on the `Object` object to filter out `Symbol` properties which is done in [lines 140-143](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/polyfill.js#L140-L143).

**Comment by triblondon** [comment]
OK, keeping a reference to a pre-patch version of a native property definitely makes sense, and we do the same in Object.defineProperty.  Is there any other benefit to the abstraction?

**Comment by JakeChampion** [comment]
There _may_ be a minification benefit but I haven't tested that assumption.

**Comment by triblondon** [comment]
OK, I guess there's no need for any code or docs changes, just wanted to discuss it.
