### ISSUE TITLE
Expose URLSearchParams on window

### ISSUE THREAD

**Issue by rupesh1** [polyfillpolyfill/polyfill-service#764]
Do you think its possible to expose the existing URLSearchParams function (available privately to the URL polyfill https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/URL/polyfill.js#L133) on the window/global object?

Example usage as a global: 
https://googlechrome.github.io/samples/urlsearchparams/index.html
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

Spec: 
https://url.spec.whatwg.org/#urlsearchparams

**Comment by triblondon** [comment]
Great idea.  This is a third party polyfill, so the best place to start is https://github.com/inexorabletash/polyfill, and if they're happy with the idea maybe raise a PR there?  If the polyfill is updated to expose URLSearchParams, we would update our copy, and add `URLSearchParams` as an alias of `URL`, since they are actually both independent web APIs but contained in one polyfill.

**Comment by rupesh1** [comment]
Hi Andrew - thanks for the quick reply. It would appear that its been available in the source polyfill since this commit https://github.com/inexorabletash/polyfill/commit/fe3084974d83c909e7d9802fa8609aab5f93cd55#diff-72d74024ea723e098405b46585936940R5301

That commit is dated Nov 2015, maybe the reference to the source `URL` polyfill could just be updated in general (and we get this for free)?

Getting `URLSearchParams` with `URL` makes perfect sense and would be ideal for my use-case.
