### ISSUE TITLE
Opera Presto versions possibly marked up incorrectly

### ISSUE THREAD

**Issue by Merri** [polyfillpolyfill/polyfill-service#860]
I was wondering why I'm not getting some default polyfills with Opera 12.17. For example, requestAnimationFrame is not served to Opera 12.17 even though it doesn't have support for it. In the config files it seems like the version target is often up to Opera 12.1, which then means versions 12.2 - 12.17 are ignored.

This also makes me wonder whether some other browser version targets are equally marked incorrectly in similar fashion.

For reference, here is what is currently served:

```
/* Polyfill service v3.11.0
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: opera/12.17.0
 * Features requested: default-3.6
 * 
 * - Array.from, License: CC0 (required by "default-3.6")
 * - Array.of, License: MIT (required by "default-3.6")
 * - _mutation, License: CC0 (required by "Element.prototype.after", "Element.prototype.append", "Element.prototype.before", "Element.prototype.prepend", "Element.prototype.remove", "Element.prototype.replaceWith", "default-3.6")
 * - Element.prototype.after, License: CC0 (required by "default-3.6")
 * - Element.prototype.append, License: CC0 (required by "default-3.6")
 * - Element.prototype.before, License: CC0 (required by "default-3.6")
 * - Element.prototype.matches, License: CC0 (required by "Element.prototype.closest", "default-3.6")
 * - Element.prototype.closest, License: CC0 (required by "default-3.6")
 * - Element.prototype.prepend, License: CC0 (required by "default-3.6")
 * - Element.prototype.remove, License: CC0 (required by "default-3.6")
 * - Element.prototype.replaceWith, License: CC0 (required by "default-3.6")
 * - Number.isNaN, License: MIT (required by "default-3.6")
 * - Object.assign, License: CC0 (required by "default-3.6")
 * - setImmediate, License: CC0 (required by "Promise", "default-3.6")
 * - Promise, License: MIT (required by "default-3.6")
 * - String.prototype.endsWith, License: CC0 (required by "default-3.6")
 * - String.prototype.includes, License: CC0 (required by "default-3.6")
 * - String.prototype.startsWith, License: CC0 (required by "default-3.6")
 * - URL, License: CC0 (required by "default-3.6") */
```

We are having problems with some more important browsers as well, such as Android 4.Xs which still seems like a plausible target for polyfill support (at least much more so than Presto based Operas as people tend to use old phones longer than old desktop browsers).

**Comment by triblondon** [comment]
@Merri we'd be delighted if you would consider helping us to improve our browser targeting. We prepared a document to help people get started if they want to correct browser targeting configuration: 

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by triblondon** [comment]
Tweeted at Opera: https://twitter.com/triblondon/status/819450967141675009

However they recently disbanded their entire devrel team so I'm not optimistic.

**Comment by zcorpan** [comment]
You can check http://www.opera.com/docs/specs/presto2.12/ for a reasonably accurate documentation of what is supported in Presto. Let me know if there's something I (or someone else at Opera) can help with here.

**Comment by triblondon** [comment]
The problem is that page doesn't tell me what *was* supported in earlier versions.  Taking the requestAnimationFrame example cited by @merri above, this is what caniuse says:

![image](https://cloud.githubusercontent.com/assets/1735391/22012290/88eea5a6-dcd6-11e6-82d5-ae948cc641c4.png)

And therefore we do this:

https://github.com/Financial-Times/polyfill-service/blob/v3.16.0/polyfills/requestAnimationFrame/config.json#L18

This may well be because caniuse doesn't have enough granularity on Opera versions, and isn't necessarily wrong.  Probably the easiest solution for us is to 'over-polyfill' Opera by targeting raf at <15.  Is there anything else that change might apply to?

**Comment by zcorpan** [comment]
It does say what was supported. It doesn't say anything about `requestAnimationFrame`, but that's probably because it *wasn't* supported (and wasn't yet part of the HTML spec or other spec that was partially implemented).

Let's see...

https://github.com/Financial-Times/polyfill-service/blob/f2098dbd6413516540379b79f309d079ab304b71/polyfills/NodeList/prototype/%40%40iterator/config.json

This seems wrong? Opera versions typically follow Chrome versions minus 13.

https://github.com/Financial-Times/polyfill-service/blob/8b5ff331e8c20e80977b28d6c8feb7acb5a42031/polyfills/HTMLCanvasElement/protoype/toBlob/config.json
https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/Array/prototype/findIndex/config.json
https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/Math/expm1/config.json
https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/Object/is/config.json
https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/Array/prototype/find/config.json
https://github.com/Financial-Times/polyfill-service/blob/69f14487641cf28b0a631fc329cbd752a26d2e16/polyfills/Number/MAX_SAFE_INTEGER/config.json
https://github.com/Financial-Times/polyfill-service/blob/69f14487641cf28b0a631fc329cbd752a26d2e16/polyfills/Number/MIN_SAFE_INTEGER/config.json
https://github.com/Financial-Times/polyfill-service/blob/188e5f72c2ecb8cb07e1da67c9a0d8c9488d91f9/polyfills/Element/prototype/append/config.json
https://github.com/Financial-Times/polyfill-service/blob/69f14487641cf28b0a631fc329cbd752a26d2e16/polyfills/Number/MAX_SAFE_INTEGER/config.json
https://github.com/Financial-Times/polyfill-service/blob/69f14487641cf28b0a631fc329cbd752a26d2e16/polyfills/Number/MIN_SAFE_INTEGER/config.json
https://github.com/Financial-Times/polyfill-service/blob/a1bd243398089d126151ad5a0000c31437ed68af/polyfills/Object/entries/config.json
https://github.com/Financial-Times/polyfill-service/blob/40180f723339a8b4bde084abf82e2b152e41b1bb/polyfills/Array/prototype/includes/config.json
https://github.com/Financial-Times/polyfill-service/blob/d3b8994b383df355fd1206fee8b7dcf983fbb3c7/polyfills/Element/prototype/after/config.json
https://github.com/Financial-Times/polyfill-service/blob/d3b8994b383df355fd1206fee8b7dcf983fbb3c7/polyfills/Element/prototype/before/config.json
https://github.com/Financial-Times/polyfill-service/blob/d3b8994b383df355fd1206fee8b7dcf983fbb3c7/polyfills/Element/prototype/replaceWith/config.json
https://github.com/Financial-Times/polyfill-service/blob/188e5f72c2ecb8cb07e1da67c9a0d8c9488d91f9/polyfills/Array/of/config.json
https://github.com/Financial-Times/polyfill-service/blob/bede2e17e2278a3e60210bf528b2b4b061cc09ba/polyfills/Array/from/config.json
https://github.com/Financial-Times/polyfill-service/blob/b54342ba3219724a55bc5ccda71d58ddcd9f7935/polyfills/IntersectionObserver/config.json

as above

https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/UserTiming/config.json

Does `<=12` target 12.17?

https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/matchMedia/config.json

Should probably be `<15`

https://github.com/Financial-Times/polyfill-service/blob/5f9a192c9d66eb02bef2f03bb14241be1ce6dbeb/polyfills/HTMLPictureElement/config.json

`<= 29` ?

https://github.com/Financial-Times/polyfill-service/blob/1ec446664dfacd4bbb1e53b6320626e9f620765b/polyfills/Map/config.json
https://github.com/Financial-Times/polyfill-service/blob/1ec446664dfacd4bbb1e53b6320626e9f620765b/polyfills/Set/config.json

should have  `opera` `< 25` ?

Others look OK.

Hope that helps!

**Comment by triblondon** [comment]
@zcorpan That's brilliant, thanks!  We'll get these updates applied.
