### ISSUE TITLE
Additional dependencies, not requested by client, must always come with `gated` flag

### ISSUE THREAD

**Issue by tinovyatkin** [polyfillpolyfill/polyfill-service#893]
For example, I'm doing feature test on my client to build needed Polyfills, and then request them with `flags=always&unknown=polyfill`, but service sends me additional polyfill dependencies ungated.

Simple test case: `Chrome 31`: `Promise` is not supported, but `Promise|always` polyfill without `|gated` flag will throw and error `Uncaught HierarchyRequestError: A Node was inserted somewhere it doesn't belong.` due to dependencies ungated polyfills.

My code, simplified:

throws `HierarchyRequestError` in Chome 31:

`https://cdn.polyfill.io/v2/polyfill$.js?flags=always&unknown=polyfill&features=Promise`

works as expected in Chrome 31:

`https://cdn.polyfill.io/v2/polyfill$.js?flags=always&unknown=polyfill&features=Promise|gated`

(`Promise` is just a test case here, the problem is in `always` flag being applied not only to the requested polyfill(s), but to their dependencies, as far I understand).

**Comment by triblondon** [comment]
This behaviour is definitely not desirable in many cases like the one you've highlighted, but it is currently the expected behaviour.  There's a proposal to change it in the next major release:
https://github.com/Financial-Times/polyfill-service/issues/892.  We'll continue to track this proposal there.
