### ISSUE TITLE
Support for performance.timing

### ISSUE THREAD

**Issue by rubencodes** [polyfillpolyfill/polyfill-service#911]
I don't know if this is something that can be added, but my app makes use of `performance.now` and `performance.timing`. Right now what I do is request the `performance.now` Polyfill from your service, and after the polyfill loads, I say:

```
if (window.performance && !window.performance.timing){
    window.performance.timing = {
        navigationStart: window.performance.now()
    };
}
```

Is there any way to add an additional polyfill for this feature?

**Comment by JakeChampion** [comment]
That would only work if the call to polyfill.io was one of the first network calls being made, correct?

**Comment by rubencodes** [comment]
Correct, it would be most accurate if it were one of the first network calls being made. Also to give proper credit: took this trick from @paulirish https://gist.github.com/paulirish/5438650.

**Comment by triblondon** [comment]
`performance.now` is the duration since `navigationStart`, isn't it?  So in that case if you have a native performance.now, polyfilling navigationStart in the way @rubencodes describes would not depend on it being loaded as the first subresource on the page.

However, I'm reluctant to attempt to polyfill this API because even with performance.now available, most of the properties of navigation timing are impossible to determine if they are not exposed - properties like `connectStart` for example.

**Comment by triblondon** [comment]
I don't think we can do anything here but feel free to reopen if you want to continue the discussion.
