### ISSUE TITLE
Galaxy S4 User Agent - "Unknown/unsupported"

### ISSUE THREAD

**Issue by rubencodes** [polyfillpolyfill/polyfill-service#912]
The Galaxy S4 on Chrome 34 and Android 5 resulted in an "Unknown/Unsupported status from Polyfill.io. Exact message returned at [this URL](https://cdn.polyfill.io/v2/polyfill.js?features=String.prototype.includes) was:

```
/* Polyfill service v3.12.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: samsung_mob/2.1.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: String.prototype.includes
 * 
 * Version range for polyfill support in this family is: >=4
 *  */
```

User agent: `Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG SCH-I545 4G Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36`

I've updated my unknown policy to polyfill to meet these edge cases, but I just wanted to know if this was an error, or if there was some reason GS4 wasn't supported. Thanks!

**Comment by JakeChampion** [comment]
It seems to be detected as samsung's browser and at a version we don't support. 

The useragent you posted looks very similar to this useragent which is from a different Samsung Galaxy S4 and it's samsung browser.

```
Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG GT-I9506-ORANGE Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36
```

If you are certain you were using chrome for android and not samsung browser then this looks to be a bug in the useragent module we use. It would need to be fixed in the uap-core project which provides the regex to the useragent module. uap-core matches [samsung browser before it matches chrome mobile](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml#L217-L229), making a fix for this a little bit tricky.

**Comment by rubencodes** [comment]
I'm not 100% sure it's Chrome for Android, I was just going off of our @getsentry logs which detected this as Chrome 34 (not sure what they use for this detection); you are probably right. Thanks for the help!
