### ISSUE TITLE
IE is not Edge

### ISSUE THREAD

**Issue by jdalton** [polyfillpolyfill/polyfill-service#916]
On the [features page](https://cdn.polyfill.io/v2/docs/features/) the display of IE includes versions 12-14 which are not IE but Edge, a totally separate browser.

<img width="195" src="https://cloud.githubusercontent.com/assets/4303/19062454/2c8986d4-89af-11e6-8e15-26fc4c7cb23b.png">

**Comment by triblondon** [comment]
All the polyfill service browsers have family identifiers, and we chose to continue using the same family identifier when IE changed to Edge, mostly because of a combination of:
- maintaining another family is more work
- IE ends at v11, Edge starts at v12, there's a sense of continuity
- to my knowledge, support in Edge is a superset of IE, so you've not dropped anything in the move to Edge that we have a polyfill for

Of course I may have been wrong in these assumptions.  We do have a note about this at the bottom of the feature table.  I appreciate that there's room for confusion here and we probably ought to change it.

**Comment by triblondon** [comment]
Sorry, hit the wrong button there.

**Comment by jdalton** [comment]
Hi @triblondon!

> maintaining another family is more work

Isn't it a fixed cost since IE is no longer updated or gaining features?

> IE ends at v11, Edge starts at v12, there's a sense of continuity

There's probably some marketing reason for not starting a browser at v1.

> to my knowledge, support in Edge is a superset of IE, so you've not dropped anything in the move to Edge that we have a polyfill for

Edge doesn't have a lot of the traditional IE-only features/code-paths. It's a separate thing.
IE 11 is really the only IE version still supported by MS and it's just waiting out the support clock.
Edge is evergreen and where MS is putting its efforts.

**Comment by JamesMGreene** [comment]
I understand and appreciate both perspectives here.

At the very least, you could certainly update the heading to "IE/Edge" for the website display, though that does not change the fact that [its config file family key is still `ie`](https://polyfill.io/v2/docs/contributing/authoring-polyfills#browsers).

**Comment by triblondon** [comment]
Actually that's a great idea and very easy to do, so let's start with that, and it should deal with the perception issue which I think is largely the root of the problem (correct me here if I'm wrong @jdalton)

**Comment by jdalton** [comment]
It's a step in the right direction.
