### ISSUE TITLE
Opera Mini: includes

### ISSUE THREAD

**Issue by zslabs** [polyfillpolyfill/polyfill-service#927]
Hi!
Similar to https://github.com/Financial-Times/polyfill-service/issues/897 I noticed that the default set passed through for Opera Mini appears to be lacking support for `includes` (this is for`String`, but I am not sure of the support for `Array`). Here's a few screens from BugSnag:

<img width="779" alt="screen shot 2016-10-11 at 9 39 32 am" src="https://cloud.githubusercontent.com/assets/1018402/19272541/f7d4ea76-8f96-11e6-9ebd-8c0add75b6ed.png">

<img width="796" alt="screen shot 2016-10-11 at 9 39 40 am" src="https://cloud.githubusercontent.com/assets/1018402/19272552/fb6511e8-8f96-11e6-9356-556025b6cda0.png">

**Comment by kdzwinel** [comment]
I hoped that opera mini is not recognized and gets no polyfills, which can be fixed by setting `unknown=polyfill`, but it's not the case. See: https://cdn.polyfill.io/v2/polyfill.js?ua=Opera/9.80%20(Android;%20Opera%20Mini/7.6.40234/37.8993;%20U;%20en)%20Presto/2.12.423%20Version/12.16 . We consider three hot fixes:
- enabling missing polyfills for all browsers `features=default,Array.from|always`
- doing UA sniffing on our servers and going `features=default|always` when opera mini is recongized
- using `callback` param to check if all polyfills are in place, and if not, force load them

**Comment by triblondon** [comment]
Adding additional browsers as targets for a particular polyfill is easy.  Here's the process:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by kdzwinel** [comment]
Thanks Andrew! I'll look into this tomorrow. Note to self: `performance.now` is also not served for Opera Mini as it should be.
