### ISSUE TITLE
fetch errors in browsers that should be covered

### ISSUE THREAD

**Issue by zslabs** [polyfillpolyfill/polyfill-service#928]
Hi all!
We're including the fetch polyfill and are noticing an elevated amount of errors in browsers that appear to be part of the list that should be covered by default.

Here's the script URL `https://cdn.polyfill.io/v2/polyfill.min.js?features=default,matchMedia,fetch,Element.prototype.placeholder,Array.prototype.includes`

and the BugSnag report:

<img width="1015" alt="screen shot 2016-10-11 at 10 35 33 am" src="https://cloud.githubusercontent.com/assets/1018402/19274611/a20a6992-8f9e-11e6-8073-e041e9ff0b26.png">

While there are several errors referencing browsers that I am unsure of on the support; like `
Sogou Explorer`, this one is mentioning Chrome seems very odd.

Thanks!

**Comment by triblondon** [comment]
Chrome 49 already has fetch natively, so it seems unlikely that in global scope `fetch` would be undefined.  Can you reproduce the error yourself, and if so could you tell us:
- The UA string (of your test browser - I do see the one above)
- Whether the polyfill response included the fetch polyfill
- Whether `fetch` is defined
- In what scope you are attempting to use `fetch` (has it been redefined at a higher scope?)

**Comment by hannesj** [comment]
I'm seeing similar issues with following browsers. Could Huawei be shipping an older android browser based browser, rather than chrome with their Android 5 phones?
- `Mozilla/5.0 (Linux; U; Android 5.1.1; fi-fi; HUAWEI Y560-L01 Build/HUAWEIY560-L01) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36`
- `Mozilla/5.0 (Linux; U; Android 5.1; en-us; HUAWEI TIT-L01 Build/HUAWEITIT-L01) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36`

**Comment by triblondon** [comment]
@hannesj Hmm, maybe.  I don't suppose you have a unit to test?  Those UAs you posted [are both normalised](https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Linux;%20U;%20Android%205.1.1;%20fi-fi;%20HUAWEI%20Y560-L01%20Build/HUAWEIY560-L01)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Mobile%20Safari/537.36) as `android/5.1`.  We [don't target fetch to that version of Android](https://github.com/Financial-Times/polyfill-service/blob/v3.16.0/polyfills/fetch/config.json#L3).  So unless you are using an `always` flag, any errors you're seeing are just issues with native implementations.

**Comment by triblondon** [comment]
@zslabs in your case the UA in your BugSnag data is normalised as `chrome/49` and [we don't target fetch to that browser](https://github.com/Financial-Times/polyfill-service/blob/v3.16.0/polyfills/fetch/config.json#L10).

So like @hannesj, I think the issue here is that you're dealing with a browser that is not really the one it claims to be. If this is a common problem for you, you could consider switching from user-agent based feature selection to client side feature detection, though at a cost of more bootstrap code in your frontend:

https://polyfill.io/v2/docs/examples#feature-detection

I don't think there's anything for us to do here, but feel free to follow up if you have anything more to add!
